### ISSUE TITLE
Updated 8/15! State of the picker and Version 6

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2326]
Please read this [blog post](https://jonathanpeterson.com/posts/state-of-my-datetime-picker-part-2.html)

There are currently 6 major tasks that will be happening as time allows.

1. Merge Tempus Dominus Core and Tempus Dominus BS 4 together. This will be the base going forward. The TD projects will be EOL’d and remain untouched. I will probably archive those repos.

2. Remove Bootstrap. Moving forward, BS won’t be a hard dependency. I’ll use a tool to grab the basic styles to generate a standalone css. The picker’s class names will probably stay the same. Hopefully, things will still look nice with BS5. 

3. Remove jQuery. This is going to be a challenge, as I mentioned during the stream to find all the places where jQuery chains are being used. A LOT of testing is going to need to be done here.

4. Swap momentjs to dayjs. I realize this will be a difficult hurdle for some to either change or have a second datetime library. I think doing this now will be easier compared to later.

5. (long term): Font Awesome 6. FA6 is in Alpha at the time of this update so it would be a good idea to prepare the default icons for this. Again, I know some people will still use older versions or Bootstrap Icons, but that’s what the options are for. :) 

6. (long term): Typescript. I started working on a jquery/bootstrap free typescript version a while back but it was a lot of work and never got it working right. I think a typescript version could happen after everything above is completed.

**Comment by tagliala** [comment]
> Task6: FA6. At the time of this writing, FA 6 is still in beta and is only available with a pro subscription. I won't update the defaults until it's released to the public and the free icons are ready to use.

👋🏼 👋🏼 

FA6 has been released :) 

I've checked the icons defined at 

https://github.com/Eonasdan/tempus-dominus/blob/4cf96112622111c3db16691ec73bae3b04d6dad1/src/js/conts.ts#L19-L27

and they are all available with the same syntax. Demos:

SVG: https://jsfiddle.net/tagliala/bfa6uhse/27/
CSS: http://jsfiddle.net/tagliala/4f8gp2wL/7/

**Comment by Eonasdan** [comment]
I have some pending code to make the change

**Comment by Eonasdan** [comment]
It's finally here everyone! Version 6 is out!

The doc have had a make over. You might find some of your bookmarks get redirected to new pages. I split out the Options and Functions docs into more readable pages.

I created a REPL that replaced the example page. This embeds a StackBlitz project and I hope that it will more easily allow for you to view the example html/js. You might notice the hash in the URL when you click on an example. In the future, I will provide a way to "export" any changes you make from the example and the hash will always produce the same code.

My next cycle back to this project (normally in 3 weeks) will likely be focused on doc clean and that kind of thing. After that, I will be trying to fix more bugs and then look at some feature requests.

Thanks for sticking it out with me. The donations I've gotten have definitely made an impact and I thank those of you who have done that.

**Comment by fw-aaron** [comment]
Wow, congratulations! I am just maintaining a project using an old version of the datetimepicker (4.14.30), trying to set a "minimum" date, just read through your blog post, then came across this issue from Oct 2020, scroll down and "It's ready!" from a few hours ago! Way to go! I hope your health keeps getting stronger and you continue to enjoy coding. Rock on!

**Comment by Eonasdan** [comment]
@fw-aaron there's a [migration tool](https://getdatepicker.com/6/migration.html) that should help you. In v6 bootstrap is no longer a dependency so in theory you should be able to use v6 with bootstrap 4/5
