### ISSUE TITLE
All my sites offline. Where is bootstrap-datetimepicker ?

### ISSUE THREAD

**Issue by mateuszjarzewski** [Eonasdan/tempus-dominus#2330]
Today all my sites went down and they are still down.
Can you tell me where I can find this file?
https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/js/bootstrap-datetimepicker.min.js

Btw. Tnx for breaking my stuff without a reason. You are a great guy.

**Comment by mateuszjarzewski** [comment]
I found this:
https://cdnjs.cloudflare.com/ajax/libs/eonasdan-bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css
https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.47/build/js/bootstrap-datetimepicker.min.js
But im not sure if its a latest verson.

**Comment by Eonasdan** [comment]
There was an announcement for over a month stuff was going to change so thanks for paying attention.

Please feel free to use something else.
