### ISSUE TITLE
Replace moment js

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2337]
It would be nice if we could simply replace moment with native datetime objects but I don't think the state of those apis is good enough for the complexity of the stuff the picker is doing.

Dayjs is a solid choice and is very similar.

**Comment by William-H-M** [comment]
Hi, quick question, the manipulation of the objects is going to be directly calling Dayjs or an interface like methods are going to be implemented?

As it would be easier for later, or just in case, to update just the specific methods and not looking through all the code

**Comment by Eonasdan** [comment]
I'm planning a plugin system to allow for extensions. If we could wrap the moment calls to functions it could allow people to keep using moment if they can't migrate.

I need to look at js file splitting. I have working examples of the TD-core and TD-bootstrap 4 working in a single file again but it's like 3k lines long. Might create a "date manipulation" module or something

**Comment by Eonasdan** [comment]
I think I'm going to remove tz and formatting support. Dayjs is already up to requiring 3 plugins just to do some of the stuff the picker was doing with moment. I'm going to try to use the native apis

**Comment by Eonasdan** [comment]
I've created a small native `Date` extension library that will not require dayjs or momentjs to be used. There still might be an issue around timezones but this tasks is otherwise done.
