### ISSUE TITLE
How to set toDisplay and toValue in Tempus Dominus V5.34.0

### ISSUE THREAD

**Issue by elivanrock** [Eonasdan/tempus-dominus#2338]
Dear Eonasdan,

I'll be glad for your help regarding an issue I'm struggling.

In my current project I'm using DateTimePickers of Tempus Dominus V5.34.0 in Javascript
and I'm using Yii2 PHP Framework for the Frontend and Backend.

I need that my user would see a display format of "DD.MM.YYYY HH:mm"
and when the user submits the form, I need than the format would be 'YYYY-MM-DD HH:mm' for the SQL Query.

In other words, I need that on the frontend it would be "DD.MM.YYYY HH:mm" format 
and when a value is selected, behind the scenes within the picker it would be 'YYYY-MM-DD HH:mm'
because of the current flow of the project.

I know that Bootstrap had a solution for it using toDisplay and toValue as the following example:

$('.datepicker').datepicker({
format: {
    /*
     * Say our UI should display a week ahead,
     * but textbox should store the actual date.
     * This is useful if we need UI to select local dates,
     * but store in UTC
     */
    toDisplay: function (date, format, language) {
        var d = new Date(date);
        d.setDate(d.getDate() - 7);
        return d.toISOString();
    },
    toValue: function (date, format, language) {
        var d = new Date(date);
        d.setDate(d.getDate() + 7);
        return new Date(d);
    }
  },
   autoclose: true 
});

I tried to set toDisplay and toValue in Tempus Dominus but it's not possible.
The solution of using momentjs is not relevant because the submit of the DateTimePicker value occurs in PHP.

How can I make that the user would see one format ('DD-MM-YYYY HH:mm') and behind the scenes the actual format would be another one ('YYYY-MM-DD HH:mm') ?

**Comment by Eonasdan** [comment]
`toDisplay` and `toValue` are not functions in any of my pickers. You'll have to format the date on the server side or format the date client side before submitting. The picker returns a moment object on the change event.
