### ISSUE TITLE
Problem with bootstrap 4.0

### ISSUE THREAD

**Issue by shaildegoam** [Eonasdan/tempus-dominus#2340]
We are using ng2-eonasdan-datetimepicker in angular app. It was working fine with Bootstrap 3.x.

Recently we upgraded to Bootstrap 4. Now only an empty popup is showing.

**Comment by Eonasdan** [comment]
`eonasdan-datetimepicker` doesn't support bs4. Try https://www.npmjs.com/package/ngx-tempusdominus-bootstrap.

**Comment by shaildegoam** [comment]
Thank you for your quick reply. We will check this new module.
