### ISSUE TITLE
Autoclose after date and time select.

### ISSUE THREAD

**Issue by shankhadevpadam** [Eonasdan/tempus-dominus#2346]
Autoclose is not working after date-time selection.

**Comment by Eonasdan** [comment]
hi this not enough information to help you. please provide a more details and a jsfiddle or stackblitz of your issue

**Comment by shankhadevpadam** [comment]
```javascript
$('#ad_start_date, #ad_end_date').datetimepicker({
    icons: {
	    time: 'far fa-clock'
    },
    format: 'YYYY-MM-DD HH:mm:ss',
});
```

**Comment by William-H-M** [comment]
@Eonasdan I think he means about the auto-close option when a date is selected, but this never worked when time was included, as It would be, personally I think, pretty annoying to select an hour and then the picker closing itself.

There're ways to do this listening to the events of change and using moment (or other libraries) and checking if current and old date are different, but is not to the scope of the 4.7.x version

**Comment by shankhadevpadam** [comment]
@Eonasdan yes same problem.

**Comment by Eonasdan** [comment]
I'd listen for the date change event and close it yourself.
