### ISSUE TITLE
need explain the version requirement for this library

### ISSUE THREAD

**Issue by arcanisgk** [Eonasdan/tempus-dominus#2348]
Please read this [blog post](https://eonasdan.com/posts/state-of-my-picker).

Can you explain what version of Bootstrap it requires for its operation?
you have a V3 and a V4 that has no consistency:

Requirements:

Bootstrap: V3
Library version: V4.17

**Comment by Eonasdan** [comment]
The picker's version isn't tied to bootstraps. It follows semver. For bs3 you need either this library at v4.17 or [version 5](https://github.com/tempusdominus/bootstrap-3). V6 is coming soonish that will be bootstrap independent.
