### ISSUE TITLE
Focus decade view on different decade

### ISSUE THREAD

**Issue by aaxc** [Eonasdan/tempus-dominus#2351]
First of all, gj, this is a really neat and nice lib.

Anyhow, I'm trying to set this up for birhday selection and really love the decade view, as it alows to quickly start the birthday selection from desired year range, but currently, when selecting deceade option, it brings up current decade with lots of future decades making the selection options for this specific purpose pointles.

![image](https://user-images.githubusercontent.com/2690743/104919548-1ad87e80-599f-11eb-9ac5-4effa1e723c1.png)

While the future years can be easily deactivated with somehting like `maxDate: moment().subtract(18, 'y'),` (for 18+ only)
it still shows decades up to 2100 so the datepicker ends up with 2 usable decades and rest are disbled.

It would be nice if the decades could not only be disabled but also hidden and max decade available would be the first unlocked one
~ or ~
an option to specify the view range, ie, instead of the current default [2000 - 2090] to something like [1920 - 2010]
~ or ~
just add focus to current decade, so with current decade beeing 2020, it would make the view to [1980 - 2060]

Although an option to specify what decade renge, would be the best, in my opinion.

**Comment by Eonasdan** [comment]
unfortunately, it would be a pain to change on the decade view works. There are two options you can use though (I'm assuming you're using v4).

[`viewDate`](https://getdatepicker.com/4/Options/#viewdate) will let you set the display back to `1980` for instance. That will move decades back on view.
There's also a `disabled` and `old` class that you could use to hide via css. 

`<span data-action="selectDecade" class="decade active" data-selection="2026">2020</span>`

Decades are located at this path given the above span
`#datetimepicker1 > div > ul > li.collapse.in > div > div.datepicker-decades > table > tbody > tr > td > span:nth-child(4)`
