### ISSUE TITLE
DateTimePicker is not assigning value given in {{ wtn.wtn_datetime }}

### ISSUE THREAD

**Issue by robertkowalski1974** [Eonasdan/tempus-dominus#2352]
Bought Creative Tim Material Design Pro Theme for Django.

When updating object datetimepicker doese not pickup given value.

`<input name="wtn_datetime" type="datetime" class="form-control datetimepicker" data-date-format="DD/MM/YYYY HH:mm" value="{{ wtn.wtn_datetime }}">`

This is script use for initialisatiion.
```
<script>
    $(document).ready(function () {
        // initialise Datetimepicker and Sliders
        md.initFormExtendedDatetimepickers();
        if ($('.slider').length != 0) {
            md.initSliders();
        }
    });
</script>s
```
Can you advice how to show field value?
thank you.

**Comment by Eonasdan** [comment]
are you sure that you actually have a value? Can you produce an example of your issue? Unfortunately, I don't know anything about django so I can only help with the js/picker side of things.

**Comment by robertkowalski1974** [comment]
Thank you for prompt reply.
Need to convert value to text first.
Please close the ticket.
Regards,

Robert Kowalski
________________________________
