### ISSUE TITLE
cannot find setValue

### ISSUE THREAD

**Issue by MarcGodard** [Eonasdan/tempus-dominus#2357]
Please read this [blog post](https://eonasdan.com/posts/state-of-my-picker).

Hi, read the blog, it doesn't help with the docs for V4.

The docs talk about a setValue function. I cannot figure out where this is or how to access it. Is there an example somewhere?

**Comment by Eonasdan** [comment]
v4 docs are here: https://getdatepicker.com/4/Options/#date

`$('#datetimepicker').data("DateTimePicker").date(value)`
