### ISSUE TITLE
$('#datetimepicker').data("DateTimePicker").date(value) Not working

### ISSUE THREAD

**Issue by MarcGodard** [Eonasdan/tempus-dominus#2359]
Hi Not sure why you moved the last issue.

I did try: `$('#datetimepicker').data("DateTimePicker").date(value)`

I got an error that function date doesn't exist.

**Comment by MarcGodard** [comment]
This is why I was looking for setValue as per your docs that you referenced.

**Comment by Eonasdan** [comment]
please stop opening new issues.
