### ISSUE TITLE
peer bootstrap@"^3.3" from eonasdan-bootstrap-datetimepicker@4.17.49

### ISSUE THREAD

**Issue by JMackCo** [Eonasdan/tempus-dominus#2368]
In my package.json I have "bootstrap": "^4.6.0" I have to remove "eonasdan-bootstrap-datetimepicker": "^4.17.49", from the package.json. After the build. I then run npm i eonasdan-bootstrap-datetimepicker --force. Everything works fine. If I include "eonasdan-bootstrap-datetimepicker": "^4.17.49" in the package.json during the initial build. It will produce an error. peer bootstrap@"^3.3" from eonasdan-bootstrap-datetimepicker@4.17.49

**Comment by Eonasdan** [comment]
closing in favor of qa
