### ISSUE TITLE
multidate don't works

### ISSUE THREAD

**Issue by alfredobp** [Eonasdan/tempus-dominus#2376]
Hello, when i use multidate option in config don' t works.
In the navigator appears:

![imagen](https://user-images.githubusercontent.com/55509379/128091806-1cf28cb6-5e89-40fb-be97-3537d25cf35b.png)

and the config json is:

[ $('.timepicker').datetimepicker({

    format: 'YYYY-MM-DD HH:mm:ss',
    inline: true,
    sideBySide: false,
    // disabledDates: disabledDate,
    enabledDates: disabledDate,
    enabledHours: enabledHour,
    maxDate:'10/10/2021',
    daysOfWeekDisabled: [6, 0],
    showClear:true,
    keepOpen:true,
    multidate:3

  });

Thanks.

**Comment by Eonasdan** [comment]
`multidate` is not an option, hence the error. What version of the picker are you using? Version 4 doesn't support multidate but version 5 does https://getdatepicker.com/5-3/Options/#allowmultidate

**Comment by alfredobp** [comment]
Ok, thanks so much.  I was using version 4. Sorry for inconvenience.
