### ISSUE TITLE
Year choices are shifted when using picker switch

### ISSUE THREAD

**Issue by nickalbrecht** [Eonasdan/tempus-dominus#2386]
The first narrowing when drilling through dates, using the picker switch, from the top level (2000-2090) down to a specific date, doesn't seem to give years for the correct range. Clicking on the year 2020 presents you with options from 2025 through to 2035, instead of 2020 through to 2030

**Comment by Eonasdan** [comment]
Hi. I think I fixed this in the commit I just made, can you verify?

**Comment by nickalbrecht** [comment]
Yup, looks like this is fixed
