### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by tdtooke** [Eonasdan/tempus-dominus#2392]
This is probably a stupid question.  Everything works except I have no icons for the popup with the year/months/time or for the span that should have some sort of calendar icon.  I attempted to do a fiddle of it but couldn't figure out how to include links to your stuff.  I have it downloaded locally for my website.  I'm pretty sure it's because I don't have anything defining fa-calendar.  I googled it and found this icon package that mentioned it.  I signed up, they sent me a link but all that did was now I have rectangular shapes where icons should be.  Do you have a cdn link you use for what I believe are the font-awesome icons?

**Comment by tdtooke** [comment]
Nevermind.....sorry to waste your time.  I downloaded font-awesome and put it on my server and changed my links to local and now it works.  Outstanding datetimepicker!

**Comment by Eonasdan** [comment]
Glad you got it working.
