### ISSUE TITLE
Picker placed in modal header for bootstrap 5

### ISSUE THREAD

**Issue by tdtooke** [Eonasdan/tempus-dominus#2393]
The current version of my site uses bootstrap 5.  My old site was bootstrap 3 and I used an older version of your picker for it.  It would display the widget overlayed over the modal body.  Is there an option already existing that I can use to do this?  I did read the options documentation but didn't find anything.  I really don't want it in the body which works.  My modal body is an iframe with a php page that shows the state of a job in my lab.  I only want people to be able to use the picker from the view of active jobs which is one of many modals I have so I want to put it in the header to keep people from being able to update things that only I should be updating.

**Comment by Eonasdan** [comment]
Hi I just published a new version of version 6 that bumps the z-index way up. In [my test](https://stackblitz.com/edit/js-akypeb?file=index.html) it seemed to work in a BS5 modal.

**Comment by tdtooke** [comment]
Thanks!!  That did it.  I am so happy.  For the time being I was using the HTML5 picker and visually it just does not blend with everything else.  Now I can push the new version!

**Comment by Lukkian** [comment]
@Eonasdan are you sure about that?
Here I am getting this with [your test](https://stackblitz.com/edit/js-akypeb?file=index.html):

![image](https://user-images.githubusercontent.com/685069/132759664-4e6776e8-54a4-434e-a902-183e4303c814.png)

**Comment by tdtooke** [comment]
Well, I looked at your example and you placed the picker in the modal body.  I have mine in the modal header and the widget overlays over the modal body and I have good visibility.

**Comment by Lukkian** [comment]
Ah, my bad!!
After changing to version 6.0.0-alpha1.0.5 the bug was gone:

![image](https://user-images.githubusercontent.com/685069/132761454-b8cd2911-5a57-4e86-862e-dec64bcbd6f5.png)

**Comment by Eonasdan** [comment]
Yay!
