### ISSUE TITLE
useTwentyfourHour not working properly

### ISSUE THREAD

**Issue by ThiagoLAMF** [Eonasdan/tempus-dominus#2395]
When setting useTwentyfourHour = true, i am getting some unexpected results.

https://stackblitz.com/edit/js-nvfv2k

When the page loads and i first click in the component, it sets the date for today: "09/09/2021, 18:13"

Then i opened the datepicker and clicked to select the hour, without using the arrows or the keyboard. Then i clicked in "01" and got the output:  "09/09/2021, 13:13".

 I think the output should be "09/09/2021, 01:13"

**Comment by hkvstore** [comment]
I found similar problem too. If the options are, e.g.
```js
      const datetimepicker1 = new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'), {
        display: { components: { seconds: true , useTwentyfourHour: true } }
      });
```
The result is like:
![err1](https://user-images.githubusercontent.com/16445695/133030450-c534d193-0e7d-4edc-b561-445ec2219040.png)

**Comment by Eonasdan** [comment]
Thanks @ThiagoLAMF for the pr. It's merged.

@hkvstore I've verified your issue and I'll have this fixed in my next pushed

**Comment by Eonasdan** [comment]
@hkvstore I think I fixed your issue in the latest release.
