### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2398]
The v6 localization feature by Intl is very nice, but it has some inconsistencies, e.g.

![locale1](https://user-images.githubusercontent.com/16445695/133031214-07385943-8145-475d-b146-c0ad52605499.png)

Localized:
![locale3](https://user-images.githubusercontent.com/16445695/133031240-769b5076-6d1d-49c3-84f6-d516313cda4e.png)

Not localized:
![locale2](https://user-images.githubusercontent.com/16445695/133031265-14b59367-8be6-437e-ba77-9ebb03422466.png)

**Comment by hkvstore** [comment]
I also find that the following commented out code is removed and therefore 'AM" and 'PM' is not localized:
```js
  meridiem(locale: string = this.locale): string {
    /*
    for some reason this stopped returning "AM/PM" and returned "in the morning"
    const dayPeriod = new Intl.DateTimeFormat(locale, {
      hour: 'numeric',
      dayPeriod: 'narrow',
    } as any)
      .formatToParts(this)
      .find((p) => p.type === 'dayPeriod')?.value;*/
    return this.hours <= 12 ? 'AM' : 'PM';
  }
```
Actually your code works, just a little change will fix it, e.g.
```js
  meridiem(locale: string = this.locale): string {
    const dayPeriod = new Intl.DateTimeFormat(locale, {
      hour: 'numeric',
      hour12: true
    } as any)
      .formatToParts(this)
      .find((p) => p.type === 'dayPeriod')?.value;
    return dayPeriod;
  }
```

**Comment by Eonasdan** [comment]
Great find on the meridiem bits, thank you. It had been working the way I had it but it was displaying "in the morning".

I'll need to investigate the localization stuff.

**Comment by Eonasdan** [comment]
Hi can you please check out the latest release? I think I've resolved this. I'm not sure how I could localize the date values.

**Comment by hkvstore** [comment]
It works. Thanks.

Regarding localizing numbers, I have created a PR #2405, please review.

**Comment by hkvstore** [comment]
> Please check this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html)

It seems that this stackblitz is not latest, it is not using the code from the PR you have merged.

**Comment by Eonasdan** [comment]
Can you try again? Looks like I have to call a purge function on jsdelivr every time I update the branch (unless I do a release) :(

**Comment by hkvstore** [comment]
It works now. Thanks. However, I have another question. After selecting a time, we can click anywhere to close the popup. When you click the calendar icon to edit the datetime, the popup still show the time part first. Should it show the calendar first?

**Comment by Eonasdan** [comment]
I'm going to close this. I opened a new issue for you comment.

**Comment by hkvstore** [comment]
The recent changes ignores localization, e.g.
```js
  /**
   * Returns two digit hours
   */
  get secondsFormatted(): string {
    return this.seconds < 10 ? `0${this.seconds}` : `${this.seconds}`;
  }
```
I understand that the following does not work because JavaScript does not always format "2-digit" as expected:
```js
  /**
   * Returns two digit hours
   */
  get secondsFormatted(): string {
    return this.format({ second: "2-digit" });
  }
```
I'd suggest using formatToParts(), e.g.
```js
  /**
   * Returns two digit hours
   */
  get secondsFormatted(): string {
    return new Intl.DateTimeFormat(this.locale, { second: "2-digit" }).formatToParts().parts.find(part => part.type == "second").value;
  }
```
Similarly for other xxxFormatted() methods.

**Comment by tirolel** [comment]
I'm not sure if @hkvstore issue is fixed in master branch but I do have same issue.

use the following locale: **ar-iq**

- Open the calendar
- Click the clock icon to select time
- Click the minutes to change minutes
- Select any minute

and the following error gets caught:
```
tempus-dominus.js:154 Uncaught RangeError: Invalid time value
    at DateTime.format (tempus-dominus.js:154)
    at Object.config.hooks.inputFormat (tempus-dominus.js:3284)
    at updateInput (tempus-dominus.js:1824)
    at Dates._setValue (tempus-dominus.js:1867)
    at Actions.do (tempus-dominus.js:1064)
    at HTMLDivElement.Display._actionsClickEvent (tempus-dominus.js:2419)
```

Also, I was wondering if #2410 fixed in master?

**Comment by Eonasdan** [comment]
@tirolel that issue has been merged. Please open a new issue
