### ISSUE TITLE
CSS Class for Toggle Period Button

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2399]
The introduction of ``Namespace.css`` is very good. It would be nice if you can add ``Namespace.css.togglePeriod`` for styling the button.

**Comment by Eonasdan** [comment]
Hi can you please check out the latest release? I think I've resolved this.

**Comment by hkvstore** [comment]
It works. Thanks.

However, please allow me to propose a little more.

Since ``classList.add()`` can add more than one class, e.g. ``span.classList.add("d", "e", "f");``, but tempus-dominus uses ``button.classList.add(Namespace.css.toggleMeridiem);``, so I cannot add more than one classes.

For example, I want to add Bootstrap button classes, I'll need to add like ``button.classList.add('btn', 'btn-primary');``.

Yes, I can create a new class to merge the styles of 'btn' and 'btn-primary', or I can add styles to 'toggleMeridiem', but it would be nice if tempus-dominus supports multiple class names, e.g.
```js
toggleMeridiem = ['toggleMeridiem'];
...
button.classList.add(...Namespace.css.toggleMeridiem);
```
then I can simply add classes by, e.g.
```js
tempusDominus.Namespace.css.toggleMeridiem = ['toggleMeridiem', 'btn', 'btn-primary'];
```

**Comment by Eonasdan** [comment]
Just for you, if you do something like `tempusDominus.Namespace.css.toggleMeridiem = 'toggleMeridiem,one,two'` before init'ing a picker it will add all the classes provided. In the future I'll probably add a more global "paint" function.

Hello, please check the development branch. This should be fixed. You can test it out on [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next).

**Comment by hkvstore** [comment]
It works fine. Thanks.
