### ISSUE TITLE
Positioning of the Time Container

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2400]
After switching to the time, the container is not positioned correctly:

![pos](https://user-images.githubusercontent.com/16445695/133032493-117b8995-03f6-4940-8057-34cfb2c6671d.png)

I found that it can be fixed by updating the position after toggling and transition, e.g. for the case ``ActionTypes.togglePicker``, add:

```js
setTimeout(() => this._context._display.popper.forceUpdate(),
          this.collapse.getTransitionDurationFromElement(this._context._display.widget.querySelector(".td-collapsing"))); // Update after transition time of .td-collapsing
```
But this requires changing the ``popper`` and ``getTransitionDurationFromElement()`` from private to public.

**Comment by Eonasdan** [comment]
Hi can you please check out the latest release? I think I've resolved this.

**Comment by hkvstore** [comment]
It works, Thanks. (Usually we do not need to place the calendar on left/right sides anyway.)

**Comment by Eonasdan** [comment]
Hello. Please check the preview branch again. That stackblitz should still work, though you might have to clear your cache.

**Comment by hkvstore** [comment]
I tried to test by ``<html dir="rtl">``, but it appears that stackblitz will change the attributes. The ``dir="rtl"`` is removed so it cannot be tested. However, I can see that the code has been updated and it should work in real cases.

**Comment by Eonasdan** [comment]
Feel free to pull down the branch or wait for the release. I'm going to close this ticket but if you have problems with it I can re-open if needed.
