### ISSUE TITLE
24 hours format is still return 12 hours format.

### ISSUE THREAD

**Issue by ketaway** [Eonasdan/tempus-dominus#2414]
https://github.com/Eonasdan/tempus-dominus/blob/69b3a649b5110764bb391634bd46880d3966fdb4/dist/js/tempus-dominus.js#L293

if set useTwentyfourHour to true still user innerDate.hoursFormatted
https://github.com/Eonasdan/tempus-dominus/blob/69b3a649b5110764bb391634bd46880d3966fdb4/dist/js/tempus-dominus.js#L2103
https://github.com/Eonasdan/tempus-dominus/blob/69b3a649b5110764bb391634bd46880d3966fdb4/dist/js/tempus-dominus.js#L2287

**Comment by SGunet** [comment]
Hi, it seems better to me, I would just change two things : start the hours with 00 and not 24, and also display two digits for the minutes

**Comment by Eonasdan** [comment]
I'll fix the 24 -> 00. I'm actually requesting a 2 digit display for the minutes from Intl so I'll have to figure out why  that's not working. I'm going to close this, you should see those other changes in the next update.
