### ISSUE TITLE
Start of week not correct

### ISSUE THREAD

**Issue by stenvdb** [Eonasdan/tempus-dominus#2418]
Based on this old ticket (https://github.com/Eonasdan/tempus-dominus/issues/1030) I assumed the start of the week would be automatically set when setting the correct locale like so:

```
new TempusDominus(document.querySelector('.js-picker-delivery'), {
      localization: {
        locale: 'nl-BE'
      },
});
```

Unfortunately this has no effect on the start of the week which should be monday based on the locale, but sticks to sunday in all cases. I'm using the new version 6 of the plugin.

**Comment by Eonasdan** [comment]
Hello, I'm going to close this in favor of #2433
