### ISSUE TITLE
Setting daysOfWeekDisabled option disables next month feature in some cases

### ISSUE THREAD

**Issue by stenvdb** [Eonasdan/tempus-dominus#2419]
I can confirm this happens only when the first day of the next or previous month is in the list of `daysOfWeekDisabled`. This bug is also reproducible on the [official examples](https://getdatepicker.com/6/examples/#disabled-days-of-the-week). If you open the datepicker you will notice it is impossible to go to the next month.

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by slightHYP** [comment]
> Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon. Please note that jsdelivr is a CDN and might have a cached copy.

I'm facing the problem right now also within your stackblitz. Just adding:

` restrictions: {
    daysOfWeekDisabled: [0, 6],
  }`

Some months and years are disabled

**Comment by Eonasdan** [comment]
Hi. I just pushed an update that I think resolves this for real.

**Comment by slightHYP** [comment]
> Hi. I just pushed an update that I think resolves this for real.

Yep! Your last version fix the issue on the months selection, but there is the same issue on the years.

![image](https://user-images.githubusercontent.com/12815732/146556604-1cfb5d30-fbc6-46f8-80a0-6a74a67542ff.png)

Thanks for the fast feedback

**Comment by William-H-M** [comment]
@Eonasdan mmm for some reason, the `.manipulate()` inside year-display when selecting decades is changing the `weekDay` at the same time it changes the year by +/- 1

So if let's say today weekDay is 5 when we do 
https://github.com/Eonasdan/tempus-dominus/blob/634794ff59c245f4efea1b2e2ff363b956449353/src/js/display/calendar/year-display.ts#L67-L69

after manipulate weekDay now is 3, and then down the road, when checking for all the possible decades after manipulate it affects the checking:

https://github.com/Eonasdan/tempus-dominus/blob/634794ff59c245f4efea1b2e2ff363b956449353/src/js/display/calendar/year-display.ts#L77-L92

Why it happens? No idea, but hope it helps in someway

**Comment by Eonasdan** [comment]
@slightHYP just pushed another update that should fix the years.

@William-H-M thanks for the report. I think this fine. I'm cloning the view date for the loop so changing the weekday shouldn't matter. Actually I'm not sure that checking any validation on views above the calendar view (except min/max) is worth doing.
