### ISSUE TITLE
Add year alongside the month in the default calendar view

### ISSUE THREAD

**Issue by mheintz** [Eonasdan/tempus-dominus#2420]
The default calendar view does not show the year of the calendar month being displayed, making it easy to lose track of the year when rapidly paging through months.  Earlier versions showed both the month and year in the header.

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

That option now accepts a full Intl format object, not just a string.
