### ISSUE TITLE
Picker size changes should be monotonic

### ISSUE THREAD

**Issue by SFr682k** [Eonasdan/tempus-dominus#2421]
**Environment:**
 - Operating System: Debian 11
 - Browser: Firefox ESR 78.15.0 (but also observable with Chromium 90)
 - TD Version 6.0.0a14

**Steps to reproduce** using the [Simple Setup example](https://getdatepicker.com/6/examples/#simple-setup):
1. Refresh the page and open the picker.
2. Switch between date and time selection.  While the time picker slides up and covers the date picker, the picker widget grows (should shrink instead); when the time picker reaches its final position, the picker suddenly becomes smaller (see Attachment/01).
3. When switching back to the date selection, the picker grows, and shrinks a tiny bit afterwards (see Attachment/02).
4. When switching to the time selection, the picker grows a tiny bit, and shrinks afterwards (see Attachment/03).
5. Switching back to date selection: same observation as in 3 (see Attachment/04).

**Expected:**  
Size changes are monotonic (i.e. picker widget is either growing or shrinking, but not both), as with v5 or v4.

**Attachment:** [tdbug.zip](https://github.com/Eonasdan/tempus-dominus/files/7436965/tdbug.zip)  
Frames from a screen recording which show the current behavior (jpg-files in respective subfolder), as well as diagrams showing the vertical position of the picker's bottom border (png-files in root folder).

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by SFr682k** [comment]
Looks good :)  Thanks for fixing!

**Comment by Eonasdan** [comment]
I have to fix an issue with this branch before I push it to the main branch, so coming soon.
