### ISSUE TITLE
Event 'hide.td' not triggered when input is empty

### ISSUE THREAD

**Issue by Jashtoyunda** [Eonasdan/tempus-dominus#2424]
When the input used for tempus dominus is empty (at start, or when emptied), "show.td" is triggered when the picker is opened, but "hide.td" is not when the picker is closed.

**Comment by William-H-M** [comment]
Hey @Eonasdan quick question on this issue, this line here on dev branch 

https://github.com/Eonasdan/tempus-dominus/blob/7ec7ade45876cecda3bf655ed3d923af6ee9a4e0/src/js/tempus-dominus.ts#L210-L227

Is to check if it's a `ChangeEvent` type, then handle the info to send `oldDate` etc., couldn't in theory either
A) Add a check for the property type and check its name for the namespace `Namespace.events.change`
B) Another function that check on a dictionary if it should go inside?

I tried A on my local code, and it works and is not breaking anything for the moment

**Comment by Eonasdan** [comment]
@William-H-M thanks for the idea. Idk why I thought I needed to check the type instead of the name.

Hello, please check the dev branch. You can test out the change on [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js)

**Comment by Eonasdan** [comment]
This fix has been published to master. If you still have an issue, please let me know.
