### ISSUE TITLE
Setting value doesn't adhere to date only format

### ISSUE THREAD

**Issue by jpeszleny** [Eonasdan/tempus-dominus#2425]
Picker is configured to only show the date (no time). However,  the time is shown when setting the picker date.
Please see this [Stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next-ptwzxm?file=index.js).

**Comment by aguevara-usc** [comment]
You are calling a new picker when you set 
`const picker = new tempusDominus.TempusDominus(document.getElementById("datetimepicker1"));`
Remove this and you should have a picker for date only.

**Comment by jpeszleny** [comment]
Thanks! That was my problem.
