### ISSUE TITLE
ChangeEvent add viewMode

### ISSUE THREAD

**Issue by tygrysio** [Eonasdan/tempus-dominus#2428]
I would like to close the picker after the date has changed.
I can do it like this.
picker1 = new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'), pickerOptions);
                        subscription = picker1.subscribe(tempusDominus.Namespace.events.change, (e) => {
                            picker1.hide();
                        });
I don't want the picker to close when I click on hour and minute arrows.
I could have prevented it if we only knew what it was like viewMode.
Maybe there is another idea for such a problem.

**Comment by Eonasdan** [comment]
Hi please check the development branch. You can preview it [on stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html)

Add this to the indexjs file

```js
document
  .getElementById('datetimepicker1')
  .addEventListener('update.td', (e) => {
    console.log(JSON.stringify(e.detail, null, 2));
  });
```

**Comment by Eonasdan** [comment]
This fix has been published to master. If you still have an issue, please let me know.
