### ISSUE TITLE
Ability to keep the input focused while popping up the picker (and navigating it) 

### ISSUE THREAD

**Issue by p-bakker** [Eonasdan/tempus-dominus#2429]
To not break keyboard navigation, I'd like to keep the focus in the input field, while I pop up the picker.

Also, when the user navigates or interacts with the picker the focus should remain in the input field.

The old bootstrap-based datetimepicker supported `focusOnShow` and allowed keyboard navigation inside the picker.

Neither of these seem supported yet currently

**Comment by Eonasdan** [comment]
closing in favor of #2390
