### ISSUE TITLE
The minutes panel remains open when minutes are selected with cursor

### ISSUE THREAD

**Issue by RenanITAO** [Eonasdan/tempus-dominus#2431]
When the `sideBySide` and `useTwentyfourHours` options are enabled and when the user selects the time with the cursor, by clicking on the minutes and then selecting the minute, it works well. But after that, when the picker is re-opened, the right panel still displays the minute selector and we cannot change the hour. The issue is reproduced on [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-f7afcq)

![image](https://user-images.githubusercontent.com/87152262/141309141-496ffeca-6462-408f-bf62-34033c4ef5f0.png)

![image](https://user-images.githubusercontent.com/87152262/141309380-20e21687-b755-4a9d-bb84-cd3a636985a0.png)

Many thanks

**Comment by SGunet** [comment]
I have the same issue when displaying a time only selector : once you select minutes, there is no way to go back to the full clock

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by RenanITAO** [comment]
> Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon. Please note that jsdelivr is a CDN and might have a cached copy.

Hello Eonasdan,

Yes it works for me, thanks.
