### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by RenanITAO** [Eonasdan/tempus-dominus#2432]
It would be nice if it was possible to change the first day of the week, for example to Monday instead of Sunday.

**Comment by Eonasdan** [comment]
Yes. Previously this was handled by momentjs. I *thought* that the native Intl would handle this based on the locale but noooooooooooooooo. ☹️ 

I'm closing this in favor of https://github.com/Eonasdan/tempus-dominus/issues/2433
