### ISSUE TITLE
Enhance DateTime offering. Please comment

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2433]
Unfortunately the native Intl is still very lacking in feature parity with other DT libs.

- [x] Start of the week
- [ ] Better formatting. The Intl format is nice but is not robust enough for some situations

**Comment by hkvstore** [comment]
Maybe [Luxon](https://moment.github.io/luxon/#/) will be useful.

**Comment by Eonasdan** [comment]
@hkvstore yeah I was providing some of the input hooks so that devs could provide their own parsing libs outside of the picker. I was hoping to avoid adding a particular dt library as a dependency.

**Comment by hkvstore** [comment]
Currently,

https://github.com/Eonasdan/tempus-dominus/blob/c535812b801d605e9d4101f72fb14b3d2dc6a718/src/js/datetime.ts#L10-L13

where Intl.DateTimeFormatOptions is:
```
    interface DateTimeFormatOptions {
        localeMatcher?: "best fit" | "lookup";
        weekday?: "long" | "short" | "narrow";
        era?: "long" | "short" | "narrow";
        year?: "numeric" | "2-digit";
        month?: "numeric" | "2-digit" | "long" | "short" | "narrow";
        day?: "numeric" | "2-digit";
        hour?: "numeric" | "2-digit";
        minute?: "numeric" | "2-digit";
        second?: "numeric" | "2-digit";
        timeZoneName?: "long" | "short";
        formatMatcher?: "best fit" | "basic";
        hour12?: boolean;
        timeZone?: string;
    }
```

Referring to [Intl.DateTimeFormat() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat), the **numberingSystem** is missing.

The numbering system is important for formatting some non-English locale (e.g. Arabic) with English digits (0-9), so I'd like to suggest improving DateTimeFormatOptions as:
```
export interface DateTimeFormatOptions extends Intl.DateTimeFormatOptions {
  timeStyle?: 'short' | 'medium' | 'long';
  dateStyle?: 'short' | 'medium' | 'long' | 'full';
  numberingSystem?: NumberingSystem;
}
```
so the format() method can format better:
https://github.com/Eonasdan/tempus-dominus/blob/c535812b801d605e9d4101f72fb14b3d2dc6a718/src/js/datetime.ts#L163-L165

**Comment by hkvstore** [comment]
When we use ``options.hooks.inputParse`` and ``options.hooks.inputFormat``, we may need to parse/format based on some custom format settings, it will be convenient if there is an option, say, ``options.display.format``, for storing some user settings.

**Comment by Eonasdan** [comment]
I could just add a `meta` object that you could add w/e props you want to.

```js
options: {
    ....
   meta: {
       dbFormat: '...',
       theCake: 'is a lie'
   }
}
```

**Comment by hkvstore** [comment]
That will be fine. Thanks.

**Comment by Eonasdan** [comment]
For those interested in the first day of the week, a new option under localization has been added. Please check  this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). 

@hkvstore The meta property has been added and so has numberingSystem

**Comment by skosnore** [comment]
I think that #2418 and  #2432 want an option to change firstWeekDay and have monday first, and not sunday, Like this:
![image](https://user-images.githubusercontent.com/94979271/143942991-2ecf2062-4fd3-44b6-af72-f039aa806414.png)
Tested startOfTheWeek: 1 and if used, you need to hide Weekdays because they get wrong.
`new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'), {  localization: { locale: 'en',startOfTheWeek: 24}});`
![image](https://user-images.githubusercontent.com/94979271/143943485-595debb6-fb8e-487f-91ce-36d5108a1691.png)
Show wrong weekdays. 29 nov is monday.

**Comment by Eonasdan** [comment]
yeah I forgot to rearrange the weekday titles :(

**Comment by Eonasdan** [comment]
I think I fixed the title shift in the dev branch.

**Comment by Eonasdan** [comment]
I'm going to close this. I've implemented a plugin system, it allows for adding new functions and overwriting existing ones. That plus the hooks should allow a wide coverage without introducing luxon or similar as a new required dependency
