### ISSUE TITLE
Input format not working as expected.

### ISSUE THREAD

**Issue by Anzil-Aufait** [Eonasdan/tempus-dominus#2435]
I want to change date format to **'MMM, DD, YYYY'**, but i can't find a way to do that. 

I'm using **tempus-dominus@6.0.0-alpha1.0.4** veersion. But when I use this version **tempus-dominus@master** it's working fine. There is problem with **Master** version, that it will not change position based on the screen resize.

**tempus-dominus@6.0.0-alpha1.0.4**: This is the stackblitz [**code**](https://stackblitz.com/edit/js-tg7yqc?file=index.js).
**tempus-dominus@master**: This is the stackblitz [**code**](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-xrt4cv?file=index.html).

Please check.

**Comment by tygrysio** [comment]
I do it like this.
inputFormat: (context, date) => {
                var formatter = new Intl.DateTimeFormat('pl-PL', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
                var dateTable = formatter.formatToParts(date);
                return dateTable[4].value + '-' + dateTable[2].value + '-' + dateTable[0].value + ' ' + dateTable[6].value + ':' + dateTable[8].value;
            }

**Comment by Eonasdan** [comment]
@Anzil-Aufait there was a breaking change in alpha14 for input format it should be `inputFormat: (context, date)`

If you change your second example to something like this it should work.

```js
hooks: {
      inputFormat: (context, date) => {
      return moment(date).format('MMM, DD, YYYY')
      }
    }
```

**Comment by Anzil-Aufait** [comment]
> @Anzil-Aufait there was a breaking change in alpha14 for input format it should be `inputFormat: (context, date)`
> 
> If you change your second example to something like this it should work.
> 
> ```js
> hooks: {
>       inputFormat: (context, date) => {
>       return moment(date).format('MMM, DD, YYYY')
>       }
>     }
> ```

@Eonasdan Hi, thank you for the replay.

Currently i'm using **tempus-dominus@6.0.0-alpha1.0.4** veersion. 


Above format is not working in this version.

**Comment by Eonasdan** [comment]
Why do you want to use an old alpha? Why not upgrade?

**Comment by Anzil-Aufait** [comment]
@Eonasdan Is it possible to share latest **CDN** link here?

**Comment by Eonasdan** [comment]
Of course

```html
 <script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"></script>

    <link
      href="
  https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
      rel="stylesheet"
    />
```

This will point to the latest code. If you prefer to be locked into a release you can exchange `master` with `v6.0.0-alpha14` in the code above

**Comment by Anzil-Aufait** [comment]
> Of course
> 
> ```
> <script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"></script>
> 
> <link
>   href="
> https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
>   rel="stylesheet"
> />
> ```
> 
> This will point to the latest code. If you prefer to be locked into a release you can exchange `master` with `v6.0.0-alpha14` in the code above

@Eonasdan Thank you for the update. Now it is working fine.

But i notice a missing feature with **Latest version** that is `master`. In this `v6.0.0-alpha14` version the `picker widget` will change it's position based on available space.

**Comment by Eonasdan** [comment]
The picker will either display on "top" or "bottom" of whatever element you attached it to. If this is not working for you please provide a screen capture or a stackblitz.
