### ISSUE TITLE
Docs for 3.x releases ?

### ISSUE THREAD

**Issue by osworx** [Eonasdan/tempus-dominus#2436]
I need the description (options) for a 3.1.3 release (I need it, don't ask why - thx).
Thought I will find it here: https://getdatepicker.com/docs/versions/
But that site does not exist!

So where are these (old) documents?

thx in advance.

**Comment by Eonasdan** [comment]
This [wayback archive](https://web.archive.org/web/20141215035446/http://eonasdan.github.io/bootstrap-datetimepicker#options) is all I can provide. I think the docs for that version where on the `gh-pages` which doesn't exist. Maybe you could find a fork that has the full source of it. Last commit was Sep 6, 2014 [a597288db638f7c959e78d29ea53db7b6b2a9149](https://github.com/Eonasdan/tempus-dominus/blob/a597288db638f7c959e78d29ea53db7b6b2a9149/src/js/bootstrap-datetimepicker.js)

Hope that's helpful
