### ISSUE TITLE
timesDiv is undefined

### ISSUE THREAD

**Issue by grahlie** [Eonasdan/tempus-dominus#2438]
Information:
- Operating system and version: macOS (Big Sur)
- Browser and version: Firefox (94.0.1)
- Version of the plugin: 6.0.0-alpha14
- Same error in this -> A test and or fork [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup)

Been a long time user of your plugin and really loving it!
I'm in the process of updating the version of the plugin to the latest version 6, did find some obstacles since I'm updating from a very old version 4.17 but that all worked out now.

One thing I did found is that when you try to disable the "clock" the togglePicker method doesn't work. Do get an console error saying:

```
Uncaught TypeError: timesDiv is undefined
_update tempus-dominus.esm.js:2085
show tempus-dominus.esm.js:2551
toggle tempus-dominus.esm.js:2660
toggle tempus-dominus.esm.js:3078
_toggleClickEvent tempus-dominus.esm.js:3035
_initializeToggle tempus-dominus.esm.js:3337
TempusDominus tempus-dominus.esm.js:3049
```

This will only occur when you have these settings for "components"
```
allowInputToggle: true,
defaultDate: new Date(),
useCurrent: false,
stepping: 5,
localization: {
    locale: 'sv-SE',
},
display: {
    sideBySide: true,
    components: {
        date: true,
        clock: false,
    },
},
restrictions: {
    minDate: new Date(),
}
```

What I've found out this has something to do action -> case ActionTypes.togglePicker inside actions.ts file. The code try to update the clock information on first render but there is no clock widget to be found. So the time-display.ts:35 will crash hard after that. this code block:
```
const timesDiv = <HTMLElement>(
      this._context._display.widget.getElementsByClassName(
        Namespace.css.clockContainer
      )[0]
);
```

Have tried analyzing the code but couldn't find a good solution or time for a pull-request right now.

Cheers,
Mathias

**Comment by Eonasdan** [comment]
Hello thanks for this report. I'm glad you like the project :). I copied your config over the stackblitz and didn't get an error. I probably do need to put a guard there.

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by grahlie** [comment]
> Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon. Please note that jsdelivr is a CDN and might have a cached copy.

Thank you Eonasdan for quick response on this one!

Will try this version out and see if this solves our problem.

**Comment by Eonasdan** [comment]
Yeah looks like this isn't fixed yet.

**Comment by Eonasdan** [comment]
Hello. I added some additional checks for this. Including that the picker will no longer accept side by side if all the clock components are disabled.
