### ISSUE TITLE
Options interface: all fields are required

### ISSUE THREAD

**Issue by ALEUT** [Eonasdan/tempus-dominus#2439]
Hi!

Currently Options interface requires all the fields to be filled in. Looks it's incorrect, even in the examples we fill part of the options.

**Comment by Eonasdan** [comment]
I assume you're talking about using it with Typescript?

**Comment by ALEUT** [comment]
Yes, with Typescript.

**Comment by SGunet** [comment]
I ran into the same issue. A temporary workaround is casting your options object :
new tempusDominus.TempusDominus(document.getElementById('dtDate'), <tempusDominus.Options>{ ... });

**Comment by Eonasdan** [comment]
Hello, please check the development branch. All the properties are now nullable.

**Comment by amigian74** [comment]
Hi.

Does this include datetime values? Because in v6.0.0-alpha14 it is only possible to set these values to undefined (maxDate for instance) and not to null.

Thx

**Comment by Eonasdan** [comment]
Hi I'm not sure I follow you. Can you provide more details?

**Comment by amigian74** [comment]
As I wrote in my comment before it is not possible to unset minDate (or maxDate) with a null value - this leads to an error. Instead you have to set undefined, which is in my opinion not a good solution.
