### ISSUE TITLE
TypeError: date.format is not a function

### ISSUE THREAD

**Issue by ALEUT** [Eonasdan/tempus-dominus#2440]
How to reproduce:
1) Select any date.
2) Clear input field.
3) Click on it to open date picker.

![image](https://user-images.githubusercontent.com/4101909/143660951-d1186a03-7fbf-494e-8bc8-905972409adf.png)

```date``` is ```""``` in this case.

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by ALEUT** [comment]
Looks fine now.
