### ISSUE TITLE
calendarWeeks, wrong weeknumber

### ISSUE THREAD

**Issue by skosnore** [Eonasdan/tempus-dominus#2441]
Showing wrong weeknumber, 2021 start on week 2. And its week 48 now, showing 49.
- Windows 10, Google Chrome, Sweden
![image](https://user-images.githubusercontent.com/94979271/143847726-4dc37b56-9315-4d76-b237-803e3f714964.png)

`new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'), { display: { calendarWeeks: true,viewMode: 'clock', components: { decades: false, year: true, month: true, date: true, hours: true, minutes: true, seconds: false, useTwentyfourHour: true } } });`

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup

**Comment by Eonasdan** [comment]
Hi. This is fixed in the main branch
