### ISSUE TITLE
Side by Side view for mobiles

### ISSUE THREAD

**Issue by wpre** [Eonasdan/tempus-dominus#2442]
I use 

```
display: {
                inline: true,
		sideBySide: true,
}
```

in my config and works fine. I was hoping that it would be responsive in smaller screens so that time selection part would go below the Calendar in mobile view. It's too little space for both windows. Is there a way, I can make it responsive? (like in previous version)

The main reason why I use side by side is because the icons are overseen by many people and I couldn't find a way to write a titles next to the icons so that it's more understandable. Is there a workaround for this? Maybe display tooltips as titles next to the icons?

**Comment by UweKubosch** [comment]
Was there a solution for this?

**Comment by wpre** [comment]
I have no solution to make it responsive but I was able to display titles next to the icons to make them more obvious.
