### ISSUE TITLE
The new option startOfTheWeek is not changing the days of the week

### ISSUE THREAD

**Issue by wpre** [Eonasdan/tempus-dominus#2443]
The new option startOfTheWeek is only changing the days (numbers) but not the (Sun,Mon,Tue etc.) titles.

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by wpre** [comment]
Hello, Thanks for your answer. Unfortunately I see no change in stackblitz (alpha15). 

It shows today (13 Dec.) under Sunday. 

This is my configuration;

```
 localization: {
    locale: 'de-DE',
    startOfTheWeek: 1,
  },
 display: {
    inline: true,
 },
```

**Comment by William-H-M** [comment]
Working right now with dev branch code, seems to be some cache issue with CDN

![imagen](https://user-images.githubusercontent.com/24443241/145861757-63cc8f64-bf0f-4abb-a83e-41943c3d601f.png)

**Comment by wpre** [comment]
It works in stackblitz now. Where can we download the new version? 
Thank you.

**Comment by Eonasdan** [comment]
You can grab it from the development branch. I'll push a new update to npm soon.
