### ISSUE TITLE
error when loading - null is not an object

### ISSUE THREAD

**Issue by michalchrzastek** [Eonasdan/tempus-dominus#2445]
Please advise what am I missing, why the error:

`null is not an object (evaluating 'this._toggle.addEventListener')`

- Operating system and version ( macOS, BigSur 11.6.1)
- Browser and version (Safari 15.1)
- Version of the plugin. 6 alpha 15
- A test and or fork [https://stackblitz.com/edit/js-9pvw1k] (https://stackblitz.com/edit/js-9pvw1k)

**Comment by William-H-M** [comment]
Hi, your error seem to be that on the index.html on line 40 you have

`data-td-toggle="datetimepicker1"`

it should be;

`data-td-toggle="datetimepicker"`

As this is the assignation instead of the ID of the picker

**Comment by michalchrzastek** [comment]
Thank you, fixed.
