### ISSUE TITLE
Closing the datepicker with ESC in v6

### ISSUE THREAD

**Issue by alexnb** [Eonasdan/tempus-dominus#2450]
It seems that reacting to key events does not work like in V4 ("removed keybindings - this might come back later" in the changelog). How can I close the datepicker on ESC?

Thanks!

**Comment by Eonasdan** [comment]
The keybindings were always messy. I'm hoping to reintroduce that option as a plugin or something like that so people could opt-in to the feature.

For now, I'd suggest listen to that key press globally and calling `.hide()` on the picker. I realize that might be less then ideal but that's all I have for you at this moment.

**Comment by Eonasdan** [comment]
I'm going to close this in favor of #2390. I'll be keeping track of keybindings and accessibility there.
