### ISSUE TITLE
Keyboard users are not able to navigate to months by pressing 'T' key or down arrow key in NVDA browse mode

### ISSUE THREAD

**Issue by sakshiupl** [Eonasdan/tempus-dominus#2451]
Pre-Requisite:
Turn on NVDA

1. Navigate to ''DateTimePicker' control using tab key and Press down arrow key to activate. 
2. Switch to browse mode using Insert + space key.
3. Press table shortcut key "T",  Focus will be visible on previous Year icon and not on the month. Also, with the down arrow keys focus is not moving to months.
4. Once focus goes on month NVDA should narrate as "table  with 3 rows and 4 columns row 1  Jan Month column 1 Jan Month".

**Comment by Eonasdan** [comment]
This seems related to #2390

**Comment by Eonasdan** [comment]
Closing in favor of the other accessibility ticket
