### ISSUE TITLE
not handle input wrong value (ever empty)

### ISSUE THREAD

**Issue by hieplq** [Eonasdan/tempus-dominus#2456]
if we input a incorrect value (or empty) to input control and lost focus then error show on console
it happen on case datepick is showed or not

- Operating system and version (linux mint 19)
- Browser and version (Chrome and Firefox)
- Version of the plugin (a-16.3)
- A test and or fork [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup)

**Comment by Eonasdan** [comment]
I don't understand your issue. Also, you're referencing an old version. Please update this issue with a fork of the stackblitz in the issue.
