### ISSUE TITLE
viewMode option not respected.

### ISSUE THREAD

**Issue by mahesh139** [Eonasdan/tempus-dominus#2466]
OS - Windows 10
Browser - Chrome, Firefox, Microsoft Edge
Version of the plugin - v6.0.0-alpha17
StackBlitz Test - https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-zmd5nc

Applied viewMode option does not work. Picker opens default calendar mode irrespective of viewMode.
Tried different viewMode values e.g. clock, months, years, decades  but none worked as expected.

Same problem on examples (View Mode)
https://getdatepicker.com/6/examples/

Problem:
Show() on Display class overwrites `this._context._currentViewMode with this._context._minViewModeNumber; `
![image](https://user-images.githubusercontent.com/11797119/149087720-47fab06c-900a-497c-be0a-4e3eae112741.png)

**Comment by Eonasdan** [comment]
Hello, please check the current version.

**Comment by mahesh139** [comment]
Thanks @Eonasdan , Its working fine in V6.0
