### ISSUE TITLE
TypeError: undefined is not an object - the calendar doesn't show

### ISSUE THREAD

**Issue by michalchrzastek** [Eonasdan/tempus-dominus#2467]
Hello,

Please assist me with this error:
Initial click on the input field throws an error in the console, the second click shows the date picker calendar but due to the error can't click any date.

`TypeError: undefined is not an object (evaluating '(this._context._display.widget.getElementsByClassName(classToUse)[0]).style')`

Operating system and version ( macOS, BigSur 11.6.2)
Browser and version (Safari 15.2)
Version of the plugin. 6, master
A test and or fork [https://stackblitz.com/edit/js-nua9k9?file=index.js] (https://stackblitz.com/edit/js-nua9k9?file=index.js)

**Comment by chriskapeller** [comment]
Hi,

I got the same error in Safari15.3 / macOS 12.2 Beta (21D48), Tempus v6.0.0-beta2
When used without time - the error is showing - see code:
    components: {
      decades: true,
      year: true,
      month: true,
      date: true,
      hours: false,
      minutes: false,
      seconds: false,
    },

If I use it without hours, minutes ans seconds its working fine!

    components: {
      decades: true,
      year: true,
      month: true,
      date: true,
    },

Hope that helps to solve this error...
All the best
chriskapeller

**Comment by amigian74** [comment]
Another bug here:

`datePickerObject.updateOptions({
            restrictions: {
                maxDate: undefined
            }
        });`

throws the following error:

Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at spread (tempus-dominus.js:1550:51)
    at tempus-dominus.js:1584:25
    at Array.forEach (<anonymous>)
    at spread (tempus-dominus.js:1562:42)
    at tempus-dominus.js:1584:25
    at Array.forEach (<anonymous>)
    at spread (tempus-dominus.js:1562:42)
    at Function._mergeOptions (tempus-dominus.js:1590:13)
    at TempusDominus._initializeOptions (tempus-dominus.js:3319:38)

**Comment by essteffan** [comment]
Any news about this this._context._display.widget.getElementsByClassName().. issue?
Thanks!

**Comment by michalchrzastek** [comment]
Thanks @chriskapeller 
Yes removing hours, minutes & seconds from components, worked.

**Comment by Eonasdan** [comment]
@michalchrzastek  your configuration is invalid with the latest version.

Is everyone having this issue using Safari? I have no way to test that

**Comment by Eonasdan** [comment]
No additional comments have been provided and I can't reproduce this.
