### ISSUE TITLE
clear() doesn't erase text of date

### ISSUE THREAD

**Issue by grassick** [Eonasdan/tempus-dominus#2472]
Calling control.clear() erases the value of the control and fires the change event, but does not erase the text box. I would expect that the text box would be kept in sync, as it is when changing a date, rather than clearing it.

To reproduce, select a date within 5 seconds. It will then attempt to clear it, but the text box doesn't change: https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-uqrvyu?file=index.js

OS: Linux, Browser: Chrome 97.0.4692.71

Version: 6.0.0-beta1

**Comment by Eonasdan** [comment]
This should be fixed in beta 5
