### ISSUE TITLE
Error while parsing date for input

### ISSUE THREAD

**Issue by AVK636** [Eonasdan/tempus-dominus#2480]
Browser Version: Firefox 91.5.1esr
TD version: v6.0.0-beta2

When creating a `TempusDominus` object while the input field already contains content you get an error like this:
```
Error: TD: Could not correctly parse "16.02.2022, 12:49 AM" to a date for input.
    TdError tempus-dominus.js:408
    failedToParseDate errors.ts:97
    _dateConversion options.ts:563
    set dates.ts:54
    _inputChangeEvent tempus-dominus.ts:481
    _initializeInput tempus-dominus.ts:382
    TempusDominus tempus-dominus.ts:51
    <anonymous> 
```
This also means, that the pre-filled date is not correctly selected in the picker overlay.
You can observe this behavior in Firefox on the [example page](https://getdatepicker.com/6/examples/). Just pick a date and then reload the page.

**Comment by AVK636** [comment]
I think the problem lies within the locale. My browser is set to german, so the locale defaults to 'de'. This results in the date being output in the format "dd.mm.yyyy". However the DateTime string parser apparently can't handle this format, which consider a bug. As a quick workaround I used the date string parser of the [vanillajs-datepicker](https://github.com/mymth/vanillajs-datepicker/blob/master/js/lib/date-format.js). My config looks then like this:
```
inputParse: (context, value) => {
  console.log(context);
  return new tempusDominus.DateTime(new Date(parseDate(value, 'dd.mm.yyyy', 'de')))
}
```

**Comment by Eonasdan** [comment]
The picker uses the native JS date object and your provide string is not a valid ISO date. I have recently updated the development branch to make it easier to deal with none-ISO formats. Take a look at the moment js plugin as an example. You can use w/e parser library you want (momentjs/dayjs/luxon) as long as you provide a date object back to the picker.

This is not a bug as I wanted to keep the picker lightweight and not add external dependencies for parsing.

**Comment by schlagmichdoch** [comment]
I was about to create a similar issue about this as it seems rather unintuitive to me.

Config from TempusDominus v5:
``` js
{
    format: "d.m.Y"
}
```

TempusDominus v6:
``` js
{
    hooks: {
        inputFormat: (context, date) => {
            return date.format({dateStyle: 'medium'})
        },
        inputParse: (context, value) => {
            return new tempusDominus.DateTime(value)
        }
    },
}
```

At first everything works smoothly as a new date is created and rendered in the format "d.m.Y". When I send this as a request that is rejected back with input data, I get the error:
``` log
Uncaught RangeError: date value is not finite in DateTimeFormat.format()
```

I understand your wish to keep the picker lightweight but I personally think your `inputParse` function / your DateTime object should at least accept the same format templates as it does with the `inputFormat` function (`{dateStyle: 'medium'}`)

**Comment by Eonasdan** [comment]
The hooks have been removed in favor of a plugin system. This allows you to provide whatever you want on top of the picker. There's a moment js example that could easily be adapted to dayjs or w/e.
