### ISSUE TITLE
don't show on input is not working

### ISSUE THREAD

**Issue by jcompagner** [Eonasdan/tempus-dominus#2483]
see my comment i made here:

https://github.com/Eonasdan/tempus-dominus/issues/2430#issuecomment-1023516459

The code deletes certain things because it wants to go copy some "data-" stuff over to the options but wants to skip 2 of them
so it deletes them. but a bit later that is still needed and used to look for to show the popup or not if you click on the input.
now its always shown because it can't find those 2 data-xxx attributes.

**Comment by Eonasdan** [comment]
Hello, please check the development branch. This should be fixed. You can test it out on [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next).

**Comment by jcompagner** [comment]
this is fixed in development branch
