### ISSUE TITLE
ship locale js files with the component that people can (dynamically) import

### ISSUE THREAD

**Issue by jcompagner** [Eonasdan/tempus-dominus#2484]
i created some first translations of a number of languages (nl, de, ro) and i am in the process of also making the it and es files

now i have those files just in my own code and import them like:

```
private loadCalendarLocale(locale: string) {
        const index = locale.indexOf('-');
        let language = locale;
        if (index > 0) {
            language = locale.substring(0, index);
        }
        language = language.toLowerCase();
        import(`./${language}.js`).then(
                (module: {default: { [key: string]: string}}) => {
                   Object.entries(module.default).forEach( ([key, value]) => {
                        this.config.localization[key] = value;
                    });
                },
                () => {
                    this.log.info('Locale ' + locale + ' for calendar not found, default to english');
                });
}
```

in my angular component

So currently i just take the language part and use that not sure if we need to be more specific that for the same language but a different country/variant we need different messages. 

But it would be nice to have those directly shipped with the component else i need to place those in my own package because i use the this component on multiply places in different packages 

[locales.zip](https://github.com/Eonasdan/tempus-dominus/files/7994721/locales.zip)

the files are very simple just export a default object thats a key value pair of the localization object.

Update: added also Italian (it) and Spanish (es) and some updates in others to the locales.zip

**Comment by Eonasdan** [comment]
Hello. I added your locales to the development branch. When I push this to master and release it, the cdn should pick those up. I'll probably include the plugins and locales in the npm package

**Comment by jcompagner** [comment]
https://github.com/Eonasdan/tempus-dominus/commit/f9eb0ac5e1630ddf6b10e4778a47a7145afebf6f#diff-51698a43408f69587f7daf17519cf2dd10e8525fa9085b437399de6f9864190cR85

is that a typo? (loacle)


for me its not fully clear how locales are loaded:

https://github.com/Eonasdan/tempus-dominus/commit/f9eb0ac5e1630ddf6b10e4778a47a7145afebf6f#diff-51698a43408f69587f7daf17519cf2dd10e8525fa9085b437399de6f9864190cR39

but i will have a bit deeper look. (maybe when there is a new release)
(did you see my other case about the click on input? i think that should be a relatively easy fix)

**Comment by Eonasdan** [comment]
typo fixed, thanks.

Yes I believe I fixed the other issues as well.

To load/use the locales you'll need to do the following

```html
 <script src='/6/js/locales/ru.js'></script> <-- load the locale file
```
```js
  tempusDominus.loadLocale(tempusDominus.locales.ru); //<--- load the locale the pool of options
  tempusDominus.locale(tempusDominus.locales.ru.name); //<--- set it globally
  const datetimepicker1 = new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'));
 datetimepicker1.locale(tempusDominus.locales.ru.name) //<-- or load it per picker
```

**Comment by jcompagner** [comment]
ah i guess i must over look something because now if "ru.js" doesn't really register itself anymore
how does it end up in tempusDominus.locales.ru ?

shouldn't there be somewhere a "import" code to dynamically import it ?
(so what i said above: https://github.com/Eonasdan/tempus-dominus/issues/2484#issue-1122924557)

**Comment by Eonasdan** [comment]
I *was* registering it automatically but it called `window.tempusDominus.loadLocale` which you suggested wasn't good (and probably wasn't). The `build:plugin` task uses rollup to put the locales in that namespace. If a locale isn't provided or you want to roll your own you could just pass in an object to `loadLocale`

**Comment by jcompagner** [comment]
ah ok, yeah i just need to dynamically load the locale messages (based on what the users locale is, see code above)
and then i need to register that one 

so i dont include any locale in the a script tag, or i include it with a hard import statement like

import locale from '@eonasdan/tempus-dominus/locales/nl';

because that makes angular to copy it in the main.js itself, and i want it to be dynamic (So a file of its own also when deployed)
This works for me already quite nice for the angular locales and numbro and so on.
