### ISSUE TITLE
Can still choose time when input is disabled

### ISSUE THREAD

**Issue by edgars-bi** [Eonasdan/tempus-dominus#2495]
- Operating system and version (Windows 10)
- Browser and version (Chrome Version 98.0.4758.82 (Official Build) (64-bit))
- Version of the plugin (6.0.0-beta1)
- StackBlitz (https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-tdzeyf)

Opens time widget when input is disabled.

**Comment by Eonasdan** [comment]
Please check this version from the dev branch https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html,index.js

**Comment by edgars-bi** [comment]
This version works perfectly!
Thanks! :)
