### ISSUE TITLE
Can type a disable date

### ISSUE THREAD

**Issue by liorFaigenzon** [Eonasdan/tempus-dominus#2496]
![image](https://user-images.githubusercontent.com/14123246/154957190-41dc0d09-1b8c-473f-9232-beb079c7001e.png)

If it is disabled, I should not be able to insert invalid date

**Comment by Eonasdan** [comment]
The picker emits an event `error.td`. I recommend you listen to that event and deal with the input. There's been debates about what to do when the input field is invalid. It was decided the picker wouldn't erase input if it was invalid. If you look at the examples, the events tab displays the error event.
