### ISSUE TITLE
noConflict has no effect ?

### ISSUE THREAD

**Issue by wuding-1104** [Eonasdan/tempus-dominus#2506]
```
const name = 'tempusDominus';
$.fn[name] = tempusDominus.jQueryInterface;
$.fn[name].Constructor = tempusDominus.TempusDominus;
const JQUERY_NO_CONFLICT = $.fn[name];
$.fn[name].noConflict = function () {
  $.fn[name] = JQUERY_NO_CONFLICT;
  return tempusDominus.jQueryInterface;
};
```

As the code in [tempus-dominus](https://github.com/Eonasdan/tempus-dominus)/[src](https://github.com/Eonasdan/tempus-dominus/tree/master/src)/[js](https://github.com/Eonasdan/tempus-dominus/tree/master/src/js)/jQuery-provider.js.  JQUERY_NO_CONFLICT set after $.fn[name]  set to tempusDominus.jQueryInterface, JQUERY_NO_CONFLICT will equals to tempusDominus.jQueryInterface, we lost the raw value of $.fn[name].

**Comment by Eonasdan** [comment]
Hello, please check the dev branch. I haven't work with jquery in a long time so I've mostly forgotten how it works.
