### ISSUE TITLE
tempus-dominus with another bootstrap theme still looks the same

### ISSUE THREAD

**Issue by AgentSmith0** [Eonasdan/tempus-dominus#2507]
Bug reports must include:

- Operating system: Any
- Browser: Any
- Version of the plugin: 6-beta2
- A test and or fork: Just use tempus-dominus with another bootstrap theme, e. g. from https://bootswatch.com and you will see that it doesn't uses the colors from the theme.

**Comment by Eonasdan** [comment]
Bootstrap is no longer a dependency. The picker has its own stylesheet. If you want to change the coloring, you'll have to overwrite the styles.
