### ISSUE TITLE
when viewMode:  'clock', uncaught TypeError: this.widget.querySelector(...) is null (index.ts:276:21)

### ISSUE THREAD

**Issue by stratacorps** [Eonasdan/tempus-dominus#2509]
Bug reports must include:

- Operating system: any, tested on Mac 12.3
- Browser: Firefox 97.0.1, Chrome 99.0.4844.51
- v6
- A test and or fork [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup)
 * replicated on StackBlitz using the following configuration:
```
new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'), {
  display: {
    viewMode: 'clock',
    components: {
        calendar: false,
        hours: true,
        minutes: true,
        seconds: false
    },
    buttons: {
        today: true,
        close: true,
        clear: true
    }
  }
});
```
When calendar components (either via calendar: false or date: false, and you select "clear selection" icon, this error is generated:<br />
```
Uncaught TypeError: this.widget.querySelector(...) is null
    _updateCalendarHeader index.ts:276
    do actions.ts:276
    _actionsClickEvent index.ts:641
    show index.ts:203
    show index.ts:202
    toggle index.ts:373
    toggle tempus-dominus.ts:83
    _toggleClickEvent tempus-dominus.ts:493
```
Another problem with viewMode: 'clock' is that warnings are generated when trying to parse the date (as there is no date is a time-only or 'clock' mode. I wasn't sure if I should report that here too, but did because it only happens in viewMode: 'clock' and, for example, there is a default value of a time in the target field (e.g. "11:00 AM").
```
Error: TD: Could not correctly parse "11:35 AM" to a date for input.
    TdError tempus-dominus.js:408
    failedToParseDate errors.ts:97
    _dateConversion options.ts:563
    set dates.ts:54
    _inputChangeEvent tempus-dominus.ts:481
```

**Comment by Eonasdan** [comment]
I couldn't reproduce this. Please *fork* the stackblitz and try to reproduce it. It's possible this has already been fixed.
