### ISSUE TITLE
[v6] AM/PM Button should be omittable via localization variable

### ISSUE THREAD

**Issue by schlagmichdoch** [Eonasdan/tempus-dominus#2510]
PM/AM Buttons seem convenient when using English dates.
However, for languages that do use the 24 hour format it should be possible to switch off the button.

![Unbenannt](https://user-images.githubusercontent.com/52242352/156676087-a375f32c-4cb2-4436-b1e1-b30b3c0c9000.PNG)

A simple setting `localisation.omitMeridiemBtn' or sth similar would be great.

Also, I liked the sideBySide design from TempusDominus v5 as its timepicker is centered and a bit bigger. Any plans to style it similarily?
![Unbenannt](https://user-images.githubusercontent.com/52242352/156676433-e78b95f2-18b9-4892-84fc-43b55bffc8e0.PNG)

- Operating system and version: Windows 10
- Browser and version: Firefox 97.0.1
- Version of the plugin: 6.0.0-beta2
- A test and or fork [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup): https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-toheah?file=index.js

**Comment by makayabou** [comment]
There is an option for that:
```
new tempusDominus.TempusDominus(#dtpicker1, {
    display: {
        components: {
             useTwentyfourHour: true,
        }
    },
}) 
```

**Comment by qbicdesign** [comment]
Agreed there is an option and for now that's an OK workaround, however since the locale information includes the time format, this could be automatic based on whether HH is used

**Comment by Eonasdan** [comment]
Other then the option as mentioned above, the only thing I could really do is test if the date parts have a `dayPeriod` value

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by Eonasdan** [comment]
The dev branch was merged and beta9 was published with a fix.
