### ISSUE TITLE
[v6] allowInputToggle seems interchanged

### ISSUE THREAD

**Issue by schlagmichdoch** [Eonasdan/tempus-dominus#2511]
The [allowInputToggle variable](https://getdatepicker.com/6/options.html#allowInputToggle) is described as
"If true, the picker will show on textbox focus. "

Appearantly, exactly the opposite behaviour is happening.
If false (default), the picker shows on textbox focus.
If true, a date is initiated but datetimepicker is not opened on textbox focus.

Bug reports must include:

- Operating system and version: Windows 10
- Browser and version: Firefox 97.0.1
- Version of the plugin: 6.0.0-beta2
- A test and or fork [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup): https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-vtwc3p

**Comment by Eonasdan** [comment]
The linked issue seems to work for me. You're a couple of versions back, could you try 5.1?

**Comment by Eonasdan** [comment]
closing for #2575
