### ISSUE TITLE
monthFormatted returns non human expected date

### ISSUE THREAD

**Issue by William-H-M** [Eonasdan/tempus-dominus#2513]
When setting data-value for the [date-display](https://github.com/Eonasdan/tempus-dominus/blob/89f69f803954fd16ef62d637e2679e814a9fe10b/src/js/display/calendar/date-display.ts#L132-L135) is expected to be on human compressible format (01-12) but is returning 0-indexed values

https://github.com/Eonasdan/tempus-dominus/blob/89f69f803954fd16ef62d637e2679e814a9fe10b/src/js/datetime.ts#L397-L399

So this makes the data-value searching for a date not to work as expected.

The good thing is, internally just this date-display.ts (easy fix) use it, the bad is if someone is using it now, It'll be a breaking change

**Comment by Eonasdan** [comment]
Right so it needs to be

` return this.month + 1 < 10 ? `0${this.month+1}` : `${this.month+1}`; `

**Comment by William-H-M** [comment]
Yeah, could be pushed on a future commit as is not something that seems to be bothering no one right now, let just keep this a reminder

**Comment by Eonasdan** [comment]
This has been published to beta5
