### ISSUE TITLE
Pass containerClone to paint

### ISSUE THREAD

**Issue by William-H-M** [Eonasdan/tempus-dominus#2514]
One of the things that would end being useful with the paint method is to modify the element properties on certain cases (change the title, text), the main reason being to add data's, currently we can add classes but using classes can be sometimes annoying to define an action or modify properties.

One example of use case is from a list of dates with a custom text to change when hover (or a jumpy animation).

So it would end with something like this?

```
const datetimepicker1 = new tempusDominus.TempusDominus(document.getElementById('datetimepicker1'));
datetimepicker1.display.paint = (unit, date, classes, element) => {
  if (unit === tempusDominus.Unit.date) {
    if (date.isSame(new tempusDominus.DateTime().manipulate(1, 'date'), unit)) {
      element.setAttribute("data-text", "Hello There!")
      classes.push('special-day');
    }
  }
}
```

And the events could be something to which most people are used to when looking for data-* (ignore the horrible event code)

```
document.querySelectorAll('[data-text]').forEach((x) => {
  x.addEventListener('mouseenter', function (event) {
    //Do something
  });
});
```

**Comment by Eonasdan** [comment]
This is done in beta 4

**Comment by William-H-M** [comment]
Confirm added on master, working as expected
