### ISSUE TITLE
Theme option

### ISSUE THREAD

**Issue by AgentSmith0** [Eonasdan/tempus-dominus#2522]
Would be nice to have a theme option. For example, values could be "light" (the default theme), "dark" (the dark theme) and "auto" (automatically detects preferred color scheme from browser).
This is very helpful, because currently the theme automatically switches and sometimes you don't want that.
Version used: v6-beta4

**Comment by redoper1** [comment]
I would suggest to separate the dark mode styles from the main SCSS file, so we could import dark mode only if we need it when we are using installation by npm. Or as suggested here to at least have option to force light mode by setting the option.

**Comment by Eonasdan** [comment]
I might end up providing four css files. Dark, light, auto, flag. Where flag is if you add `dark` as a css class to the element then those styles will be applied.

**Comment by AgentSmith0** [comment]
Thank you very much for your work! Maybe you could also publish a css file that uses bootstraps css variables to style the datetime picker, for using this library easier with bootstraps theme.

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by Eonasdan** [comment]
The dev branch was merged and beta9 was published with a fix.
