### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2524]
The recent changes broke localization, e.g.
```js
  /**
   * Returns two digit seconds
   */
  get secondsFormatted(): string {
    return this.seconds < 10 ? `0${this.seconds}` : `${this.seconds}`;
  }
```
I understand that the following does not work because JavaScript does not always format "2-digit" as expected:
```js
  /**
   * Returns two digit seconds
   */
  get secondsFormatted(): string {
    return this.format({ second: "2-digit" });
  }
```
I'd suggest using formatToParts(), e.g.
```js
  /**
   * Returns two digit seconds
   */
  get secondsFormatted(): string {
    return new Intl.DateTimeFormat(this.locale, { second: "2-digit" }).formatToParts().find(part => part.type == "second").value;
  }
```
Similarly for other xxxFormatted() methods.

**Comment by Eonasdan** [comment]
`new Intl.DateTimeFormat('en-US', { second: "2-digit" }).formatToParts().find(part => part.type == "second").value;` returns '3' for me.

What's broken about the way it is?

**Comment by hkvstore** [comment]
1. For example, if locale is "ar-BH", and the second is 3, secondsFormatted() will returns "03", but it should be "٠٣".
2. For unknown reason, ``minute: "2-digit"`` is also required to make JavaScript return 2-digits, e.g.
```js
  /**
   * Returns two digit hours
   */
  get secondsFormatted(): string {
    return new Intl.DateTimeFormat(this.locale, { minute: "2-digit", second: "2-digit" }).formatToParts().find(part => part.type == "second").value;
  }
```

**Comment by Eonasdan** [comment]
Please check this template and verify that it looks good.

```js
template = {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    }
```

I think I'll save this template and make all the `*formatted` pull from the `parts` using this template.

**Comment by hkvstore** [comment]
It looks fine, I believe you'll also add ``hour12: false`` for ``hoursFormatted()`` and ``hour12: true`` for ``twelveHoursFormatted()``. Thanks.

**Comment by Eonasdan** [comment]
This has been published to beta5
