### ISSUE TITLE
undefined is not an object (evaluating 'hour.length') on Safari

### ISSUE THREAD

**Issue by pagano** [Eonasdan/tempus-dominus#2534]
- macOS BigSur 11.2.3
- Safari 14.0.3
- Version of the plugin: 6.0

In this example you can reproduce the behavior: https://stackblitz.com/edit/tempus-dominus-v6-simple-setup

When you click on the Clock to set the time the error occurs in this line:

 get twelveHoursFormatted(): string {
    let hour = this.parts().hour;
    **if (hour.length === 1) hour = `0${hour}`;**
    return hour;
  }

The problem occurs inside parts() function, which doesn't return time parts. Specifically this code:

new Intl.DateTimeFormat(locale, template).formatToParts(this)

Which returns only date parts (see attachment)

<img width="1440" alt="Captura de Pantalla 2022-04-06 a la(s) 12 08 25" src="https://user-images.githubusercontent.com/4493020/162008073-8457e086-b047-4db8-adda-2e247070b4cc.png">

**Comment by pagano** [comment]
Solved using useTwentyfourHour: true

**Comment by Eonasdan** [comment]
5.1 hotfix was just publish. Should fix the formatting bugs
