### ISSUE TITLE
6.0.0-beta5 distribution package doesn't appear to be completely up to date

### ISSUE THREAD

**Issue by scoldwell** [Eonasdan/tempus-dominus#2536]
We just pulled down the latest 6.0.0-beta5 and noticed that several of the packages in dist/js are out of date.  You can also see the issue here:

https://github.com/Eonasdan/tempus-dominus/tree/master/dist/js

For the following, the header comment still indicates beta4.  May just need the header comment updated with the correct version as I don't believe anything changed in this module for beta5:
- node_modules/@eonasdan/tempus-dominus/dist/js/jQuery-provider.js
- node_modules/@eonasdan/tempus-dominus/dist/js/jQuery-provider.min.js

For the following, the header comment still indicates beta4.  These were initially included in our application by default, but did not have the fixes from beta5:
- node_modules/@eonasdan/tempus-dominus/dist/js/tempus-dominus.esm.js
- node_modules/@eonasdan/tempus-dominus/dist/js/tempus-dominus.esm.min.js

We were able to work around it by including the updated js file specifically, but wanted you to be aware that there might be a problem with your release procedure.

Thanks for all your effort!

**Comment by Eonasdan** [comment]
5.1 hotfix was just publish.
