### ISSUE TITLE
Hour-Time-Selector shows "undefined" when using 24H-Format

### ISSUE THREAD

**Issue by clam0r** [Eonasdan/tempus-dominus#2539]
When using `components: { useTwentyfourHour: true }` the timeselector shows "undefined" instead of the current hour. Both the up and down arrow still work and display the current result in the inputfield. No error is displayed in the console.

Operating system and version (Windows, macOS, Android, iOS)
- MS Windows 10 Version 10.0.19044.1586

Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- Firefox 98.0.2 (64-Bit) and Microsoft Edge Version 100.0.1185.36. Apple iOS Safari works though.

Version of the plugin. There is no support for version 3, 4 or 5.
- current from https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js

![grafik](https://user-images.githubusercontent.com/39246790/163031794-0578bd3d-0e49-4e22-81c2-d760def5d813.png)

**Comment by bisvillallai** [comment]
Same here, any workaround will be appreciate

**Comment by Dicusar94** [comment]
Following , please fix 😉

**Comment by William-H-M** [comment]
This is related with the template of #2524 is currently

```
const twoDigitTwentyForTemplate = {
  hour12: false
}
```

Should be:

```
const twoDigitTwentyForTemplate = {
  hour: '2-digit',
  hour12: false
}
```

**Comment by Eonasdan** [comment]
5.1 hotfix was just publish. Should fix the formatting bugs
