### ISSUE TITLE
jQuery-provider.js

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2547]
Should https://github.com/Eonasdan/tempus-dominus/blob/9c995012101ad70ce1ce1fcbb6903023c6beec6b/src/js/jQuery-provider.js#L22 be the follows?

```js
option = $.extend({}, tempusDominus.DefaultOptions, option);
```

and this line https://github.com/Eonasdan/tempus-dominus/blob/9c995012101ad70ce1ce1fcbb6903023c6beec6b/src/js/jQuery-provider.js#L61 be the follows?

```js
$selector.data($.extend({}, $selector.data(), $(this).data()));
```

**Comment by Eonasdan** [comment]
According to [the docs](https://api.jquery.com/jquery.extend/)

> Keep in mind that the target object (first argument) will be modified, and will also be returned from $.extend()

Based on that, I think it's fine. Is there an issue you are experiencing that makes you think that's not correct?

**Comment by hkvstore** [comment]
> According to [the docs](https://api.jquery.com/jquery.extend/)
> 
> > Keep in mind that the target object (first argument) will be modified, and will also be returned from $.extend()

That's true, but the existing code is:

https://github.com/Eonasdan/tempus-dominus/blob/9c995012101ad70ce1ce1fcbb6903023c6beec6b/src/js/jQuery-provider.js#L22

**Comment by hkvstore** [comment]
Should it be the follows?
```js
option = $.extend({}, tempusDominus.DefaultOptions, option);
```

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Can you check now?

**Comment by hkvstore** [comment]
Thanks.

The following line should also be updated?

https://github.com/Eonasdan/tempus-dominus/blob/50a715028c495eb725f584971b87a60fad01fbf8/src/js/jQuery-provider.js#L61

**Comment by Eonasdan** [comment]
so `$(this).data() = $.extend({}, $selector.data(), $(this).data());` ?? I think I mentioned before I haven't used jQuery in a long time
