### ISSUE TITLE
The .hoursFormatted() method

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2548]
The line https://github.com/Eonasdan/tempus-dominus/blob/9c995012101ad70ce1ce1fcbb6903023c6beec6b/src/js/datetime.ts#L358 may not be correct:

1. If numbering system of the locale is not 'latn', the ``.hour`` property will not be '24', the comparison will fail.
1.  Return '00' ignores non 'latn' numbering system.

**Comment by Eonasdan** [comment]
Do you have an example?

**Comment by hkvstore** [comment]
Currently:
https://github.com/Eonasdan/tempus-dominus/blob/9c995012101ad70ce1ce1fcbb6903023c6beec6b/src/js/datetime.ts#L357-L358

If locale is Arabic, e.g. "ar-IQ", ``formatted`` is ``'٢٤'`` (which is '24' in Arabic), the condition in the second line will never be met. And the return value should be ``'٠٠'`` (which is '00' in Arablic), not '00'.

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by hkvstore** [comment]
Thanks. It is fine.

**Comment by Eonasdan** [comment]
The dev branch was merged and beta9 was published with a fix.
