### ISSUE TITLE
Days and months inverted on manually date set with Locale IT

### ISSUE THREAD

**Issue by JacopoBasilico** [Eonasdan/tempus-dominus#2571]
Sorry i saw that a bug like this had already been posted

Thank you

Original:

Hi Man, thanks for your work, I wanted to report a bug: if the Locale is set to IT Italy (dd/mm/yyyy) and manually write a date like 11/01/2022 and press enter, the date is taken as 01/11/2022 reversing days and months.
Thanks
Greetings from Italy
Jacopo

**Comment by Eonasdan** [comment]
closing in favor of #2537
