### ISSUE TITLE
custom date format generate an error while creating a new instance of TempusDominus

### ISSUE THREAD

**Issue by unitnmoris** [Eonasdan/tempus-dominus#2574]
As per documentation parseInput can be overrriden by replacing the funtion picker.dates.parseInput=function(val){...} with a custom functon. (I couldn't find any other way to override this function)
Unfortunately this override can only happen after the creation of the TempusDominus instance ( new tempusDominus.TempusDominus(element,options) )

If the html input, where the calendar is attached, is pre-populated with a custom value, the default picker.dates.parseInput function is called upon the construction of the TempusDominus instance and an error like "Error: TD: Could not correctly parse "25/05/2022 13:20" to a date for input."

The best way to fix this problem could be to add the hook in the initialization options object

Best

**Comment by Eonasdan** [comment]
Please provide a stackblitz
