### ISSUE TITLE
updateOptions() not working - previous options are lost

### ISSUE THREAD

**Issue by ericsua** [Eonasdan/tempus-dominus#2578]
v6-beta7

The method `updateOptions()` is not working when executed more than once on a single picker.
If I execute `updateOptions()` two times on a single date time picker, the previous options are lost
e.g.
```
linked1.updateOptions({ 
    display: { 
        viewMode: "clock",
        components: {
          useTwentyfourHour: true,
          decades: false,
          year: false,
          month: false,
          date: false,
          hours: true,
          minutes: true,
           seconds: false,
        }
    } 
})
linked1.updateOptions({ restrictions: { minDate: new Date() } })
```
I expect that after the second update the picker has the restriction AND the viewMode as clock, but it's not happening.
I read the docs and the source code and it seems that it should merge the new options with the previous ones, unless reset=true is provided.

[example on StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-next-kt1t2b?file=index.js)

**Comment by Eonasdan** [comment]
Hello. I just pushed some changes that should fix this.

**Comment by ericsua** [comment]
I can confirm that now it's working as expected. Thanks!
