### ISSUE TITLE
`viewMode: 'clock'` defaults to date view if date components are not deactived

### ISSUE THREAD

**Issue by cdubz** [Eonasdan/tempus-dominus#2583]
- Operating system and version: macOS 12.4
- Browser and version: Firefox 102.0b4, Chrome 102.0.5005.61, Safari 15.5 (17613.2.7.1.8)
- Version of the plugin: 6 🔥 
- StackBlitz fork: https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-yytw2n

I'm hoping to have a picker that supports all the default time _and date_ components but that opens to the `clock` view mode initially. If I set the picker options as  simply --

```js
{ display: { viewMode: 'clock' } }
```

the picker opens in the default `calendar` view mode expect that toggles are reversed (i.e., the calendar toggle has a calendar icon and the label is "Select Date" and when I change to the time selector the toggle is a clock icon and the label is "Select Time").

The `clock` view mode works as expected if the date components are disabled (though I think this is just the default behavior).

**Comment by cdubz** [comment]
Doing a little digging around... this seems to be cause, at least in part, by this logic during configuration initialization:

https://github.com/Eonasdan/tempus-dominus/blob/b54bb336bf12fd04406affe5f2bcbe34640df2d0/src/js/tempus-dominus.ts#L355-L364

In my use case `CalendarModes[this.optionsStore.currentCalendarViewMode].name` would be the default `calendar` and `newConfig.display.viewMode` would be `clock`.

`CalendarModes` does not have a `clock` entry:

https://github.com/Eonasdan/tempus-dominus/blob/3ab219ddb96d90475d581a22b069209cd1acbada/src/js/utilities/calendar-modes.ts#L5-L35

So the result of the `Math.max` operation above ends up being the default `this.optionsStore.minimumCalendarViewMode` (`0` = `calendar`).

It doesn't seem like it would make sense to just add `clock` to `CalendarModes` so maybe some special handling is needed in the config initialization conditional?

**Comment by cdubz** [comment]
It seems the configuration initialization process is not at fault/relevant here -- #2584 instead fixes the issue by incorporating a check of the options in the `show` event where there is already special logic for handling the "clock only" use case.

**Comment by Eonasdan** [comment]
This is a bug that I have pending code to fix.

**Comment by cdubz** [comment]
Ok -- feel free to scrap that PR. Thanks!

**Comment by Eonasdan** [comment]
Hi, please check the latest version
