### ISSUE TITLE
Problem on opening the time picker from calendar view

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2594]
How to reproduce:
- Go to [Simple Setup](https://getdatepicker.com/6/examples/#simple-setup)
- Click the calendar icon to open the date time picker
- Click the clock icon at the bottom of the popup, the date time picker reloads itself and the clock icon at the bottom is wrongly changed to calendar icon (wrongly)
- Click the calendar icon at the bottom of the popup, the time picker now shows, but the icon at the bottom is now a clock icon (it should be a calendar icon indicating that we can go back to the calendar view)

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by Eonasdan** [comment]
The dev branch was merged and beta9 was published with a fix.
