### ISSUE TITLE
DateView Previous/Next buttons disabled

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2595]
### Discussed in https://github.com/Eonasdan/tempus-dominus/discussions/2589

<div type='discussions-op-text'>

<sup>Originally posted by **cwolcott** June 15, 2022</sup>
I just noticed an issue with the previous/next buttons on the Date View after I perform the following.

**Description:**
- The date picker is configured to only allow a date to be selected between today and 3 weeks from today.
- Returns a date in the format of YYYY-MM-DD
- I have also configured css to show bright blue selectable dates (current month) light blue selectable dates (next month)

**Steps:**
   1a - Open date picker
   1b - Select Next (Navigates to July), Select Previous (Navigates to June) **(It works)**
   1c - Close date picker
   1d - Open date picker 
   1e - Select Next (Navigates to July), Select Previous (Navigates to June)s **(Still works)**
   1f - Select a valid date in the current or next month
   1g - Date picker automatically closes
   1h - Open date picker 
   1i - Select Next (To navigate to July) **(Doesn't work)**
   1j - Close date picker

**Continue with the following and it works again:**
   2a - Don't reset and open date picker
   2b - Click on June 2022 to show month view
   2c - Select June
   2d - Select Next (Navigates to July), Select Previous (Navigates to June)  **(It works again)**

Here is an [example](https://stackblitz.com/edit/js-45hjcp?file=readme.txt)</div>

**Comment by Eonasdan** [comment]
Hello @cwolcott, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by cwolcott** [comment]
Looks good
[https://stackblitz.com/edit/issue2596-verify](https://stackblitz.com/edit/issue2596-verify)
