### ISSUE TITLE
Mismatch types: display.components.useTwentyfourHour

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2599]
https://github.com/Eonasdan/tempus-dominus/blob/50a715028c495eb725f584971b87a60fad01fbf8/src/js/utilities/default-options.ts#L48

The above change causes the following error:

*Uncaught Error: TD: Mismatch types: display.components.useTwentyfourHour has a type of boolean instead of the required undefined*

**Comment by Eonasdan** [comment]
opps. thanks. can you check now?

**Comment by hkvstore** [comment]
It is fine. Thanks.
