### ISSUE TITLE
".hooks" in not a known option

### ISSUE THREAD

**Issue by aldak** [Eonasdan/tempus-dominus#2601]
Hello, I'm trying to make own parse method using hooks.inputParse

```
const td = new tempusDominus.TempusDominus(collection[i],{
		display: { keepOpen: false},
		hooks: { 
			inputParse: (td, value) => {  
				alert(value);
				return new tempusDominus.DateTime(value);
			}
		}
	});
```

But I'm getting error 
`Uncaught Error: TD:: ".hooks" in not a known option.
    at ErrorMessages.unexpectedOptions (errors.ts:27:19)
    at OptionConverter.spread (optionConverter.ts:138:37)
    at OptionConverter._mergeOptions (optionConverter.ts:395:25)
    at TempusDominus._initializeOptions (tempus-dominus.ts:321:33)
    at new TempusDominus (tempus-dominus.ts:50:10)
    at hany_functions.js:47:13`

**Comment by Eonasdan** [comment]
Hooks where removed in beta 4 in favor of plugins. Please see the [change log](https://getdatepicker.com/6/change-log.html) and the [momentjs plugin docs](https://getdatepicker.com/6/plugins/moment.html)

**Comment by Eonasdan** [comment]
there's a `meta` object on the config that you can set to whatever you want. At that point you could use `this.optionsStore.options.meta.myFormat`. You don't have to use moment, btw. You do or use whatever you want to format it. 

You could get the format some other way as well. The momentjs plugin is an easy to adapt example.

There's also discussions on #2537 on expanding the date time object to support other formats.
