### ISSUE TITLE
Issue Linked pickers

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2611]
### Discussed in https://github.com/Eonasdan/tempus-dominus/discussions/2605

<div type='discussions-op-text'>

<sup>Originally posted by **cwolcott** July 11, 2022</sup>
I not sure if this is a bug, if I am missing a call or just the way it is.

**Description:**
   - The linked pickers are configured to make sure the start date <= end date, like the example
   - I would like the picker to show the current month/year if a date is currently set.
  
**Steps:**
   1a - Select Button [A] which sets the Start Date (2022-05-05) then the End Date (2022-09-09)
   1b - Click the calendar icon for End Date, the calendar is viewing September 2022 and shows the set day 9th.
   1c - Click the calendar icon for Start Date, the calendar is viewing the current month (July 2022)
   1d - I was hoping it would show the month of the set date (May 2022)

   2a - Select Button [B] which sets the End Date (2022-09-09) then the Start Date (2022-05-05) 
   2b - Click the calendar icon for Start Date, the calendar is viewing May 2022 and shows the set day 5th.
   2c - Click the calendar icon for End Date, the calendar is viewing the current month (July 2022)
   2d - I was hoping it would show the month of the set date (September 2022)

   What can I do so that when the picker is shown the view shows the current month set?

Here is an [example](https://stackblitz.com/edit/js-rtrcjk?file=readme.txt)

The same issue happens with the [Tempus Dominus Examples: Linked Picker](https://getdatepicker.com/6/examples/#linked-pickers)

**Steps:**
   3a - Pick a **From Date** of July 27, 2022
   3b - Pick a **To Date** of Nov 12, 2022
   3c - Click the calendar icon for the **From Date**, the calendar is viewing the To Date month November 2022 and not July 2022.
</div>

**Comment by cwolcott** [comment]
Are you considering this for any upcoming releases?

**Comment by Eonasdan** [comment]
Yes. My free time has been limited recently.

**Comment by Eonasdan** [comment]
I please check out this branch. I think I've fixed this issue https://github.com/Eonasdan/tempus-dominus/tree/2611-issue-linked-pickers

**Comment by Eonasdan** [comment]
Here's a [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-2611?file=index.js,index.html)

**Comment by cwolcott** [comment]
Will check it out today

**Comment by Eonasdan** [comment]
This was released with 6.2.6

**Comment by cwolcott** [comment]
Thank you so much.  This works perfectly.
