### ISSUE TITLE
dates.setValue with parsed input does not maintain the set locale for day/month (painted) labels

### ISSUE THREAD

**Issue by polygonwood** [Eonasdan/tempus-dominus#2619]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

default Locale is set to 'ru' (example)

    const picker = new global.Tempusdominus.TempusDominus(document.getElementById('myDateTimeElem'));

Now I want to change the value, e.g. to 'now' :  
    
    const parsedDate = picker.dates.parseInput(new Date());
    // parsedDate.setLocale('nl');
    picker.dates.setValue(parsedDate);

**The second (commented) line is mandatory for proper working otherwise the locale remains selected (e.g. for hovering labels) but the rendered (painted) names of days and months goes back to default (English)**

Suggestion : 

- either document that this is necessary
- either create the DateTime object with the set locale

### StackBlitz fork

[https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-t18nor?file=index.js](url)
//using "window" is just for the stackblitz, you do not need to do this
const nlLoc = {
  today: 'Vandaag',
  'clear': 'Verwijder selectie',
  'close': 'Sluit de picker',
  'selectMonth': 'Selecteer een maand',
  'previousMonth': 'Vorige maand',
  'nextMonth': 'Volgende maand',
  'selectYear': 'Selecteer een jaar',
  'previousYear': 'Vorige jaar',
  'nextYear': 'Volgende jaar',
  'selectDecade': 'Selecteer decennium',
  previousDecade: 'Vorige decennium',
  nextDecade: 'Volgende decennium',
  previousCentury: 'Vorige eeuw',
  nextCentury: 'Volgende eeuw',
  pickHour: 'Kies een uur',
  incrementHour: 'Verhoog uur',
  decrementHour: 'Verlaag uur',
  pickMinute: 'Kies een minute',
  incrementMinute: 'Verhoog  minuut',
  decrementMinute: 'Verlaag minuut',
  pickSecond: 'Kies een seconde',
  incrementSecond: 'Verhoog seconde',
  decrementSecond: 'Verlaag seconde',
  toggleMeridiem: 'Schakel tussen AM/PM',
  'selectTime': 'Selecteer een tijd',
  'selectDate': 'Selecteer een datum',
  dayViewHeaderFormat: { month: 'long', year: '2-digit' },
  'locale': 'nl',
  'startOfTheWeek': 1
}
tempusDominus.locales = {}
tempusDominus.locales['nl'] = {
  name: 'nl',
  localization: nlLoc
};
tempusDominus.loadLocale(tempusDominus.locales.nl);
tempusDominus.locale('nl');

window.datetimepicker1 = new tempusDominus.TempusDominus(
  document.getElementById('datetimepicker1'),
  {
    //put your config here
  }
);

document.getElementById(
  'info'
).innerHTML = `Your browser's locale is ${navigator.language}.<br/>
You are using version ${tempusDominus.version}`;

const parsedDate = window.datetimepicker1.dates.parseInput(new Date());

// uncomment the next line to get the Dutch translations for days and months labels
// parsedDate.setLocale('nl');

// commenting the next line just renders the default locale example, which has expected days/months labels
window.datetimepicker1.dates.setValue(parsedDate);

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.0.0-beta9

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Hi. Is this still an issue with the latest version?

**Comment by Eonasdan** [comment]
Please let me know if this is still an issue and I'll reopen it
