### ISSUE TITLE
Calling updateOptions() causes scrolling to jump.

### ISSUE THREAD

**Issue by MaxwellDAssistek** [Eonasdan/tempus-dominus#2621]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Calling updateOptions() on a datetimepicker that is at the bottom of a scrollable div causes the scroll to jump due to the datetime picker being recreated.

![2022-08-11 12-50-04](https://user-images.githubusercontent.com/61429558/184190570-b01fd6e9-c579-44f6-9b90-08244d74c58e.gif)

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-v78952?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.0.0-beta9

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by MaxwellDAssistek** [comment]
Even if I work around this issue by temporarily setting up a min-height css property that equals to the height of the div before updateOptions, the picker being reloaded is MUCH too noticeable. 

An application that I am working on requires essentially 2 pickers to be linked so one cannot be earlier than the other and vice versa. the way I used to do this in previous versions of TD was to update the max/minDate as one of the pickers changes, however in this version it is very noticeable. 
![2022-08-11 16-39-43](https://user-images.githubusercontent.com/61429558/184238681-3c9ff3fc-e6bd-4026-b038-5015c07111ce.gif)
(Due to the low framerate of the gif it is less noticeable, but in reality it is very noticeable on every change of one of the pickers)

**Comment by Eonasdan** [comment]
Hi. I believe I have fix this in the attached branch. Please check out this [StackBlitz](https://stackblitz.com/edit/typescript-8ainhq?file=index.html)

**Comment by MaxwellDAssistek** [comment]
I am still able to reproduce the issue very easily. On Firefox if you start clicking it multiple times in a row it still flashes. I also tested the same StackBlitz on Chrome and apparently it is even easier to reproduce there. It might be marginally better, but it still doesn't look like the core issue is resolved. I tried also updated my app to the latest version to the same result. Still same flickering.

**Comment by MaxwellDAssistek** [comment]
@Eonasdan Should I open another issue that focuses on the flickering rather than the scrolling?

**Comment by Eonasdan** [comment]
No. I merged what I had and it auto closed. I'll try to keep improving this.

**Comment by Eonasdan** [comment]
Hi @MaxwellDAssistek I'm looking at this again. I see this still happens on the SB even with the latest, however locally, it's not an issue. Are you still experiencing this?

**Comment by MaxwellDAssistek** [comment]
@Eonasdan Very much so. We've done our best to make it less noticeable with min-height/min-width and/or loading screens, but its still definitely an issue for us.

**Comment by Eonasdan** [comment]
Thanks for letting me know. Can you try [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-2621-updateoptions-jumping?file=index.js,index.html) based on [this branch](https://github.com/Eonasdan/tempus-dominus/tree/2621_updateoptions_jumping)

**Comment by Eonasdan** [comment]
This has been released
