### ISSUE TITLE
Previous/Next icons for RTL

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2625]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

Please consider RTL for Previous/Next icons, I'd suggest:

```js
  /***
   * Builds the base header template with next and previous icons
   * @private
   */
  getHeadTemplate(): HTMLElement {
    const calendarHeader = document.createElement('div');
    calendarHeader.classList.add(Namespace.css.calendarHeader);

    const previous = document.createElement('div');
    previous.classList.add(Namespace.css.previous);
    previous.setAttribute('data-action', ActionTypes.previous);
    previous.appendChild(
      this._iconTag(this.optionsStore.options.display.icons[document.documentElement.dir === 'rtl' ? 'next' : 'previous']) //***
    );

    const switcher = document.createElement('div');
    switcher.classList.add(Namespace.css.switch);
    switcher.setAttribute('data-action', ActionTypes.changeCalendarView);

    const next = document.createElement('div');
    next.classList.add(Namespace.css.next);
    next.setAttribute('data-action', ActionTypes.next);
    next.appendChild(
      this._iconTag(this.optionsStore.options.display.icons[document.documentElement.dir === 'rtl' ? 'previous' : 'next']) //***
    );

    calendarHeader.append(previous, switcher, next);
    return calendarHeader;
  }
```

### Motivation and context

Support RTL languages

**Comment by Eonasdan** [comment]
Can't the existing localization handle this? Set the next icon to a previous icon, set title to the correct text?

**Comment by hkvstore** [comment]
But the icon is under options:
https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/utilities/options.ts#L33

**Comment by Eonasdan** [comment]
I was reconsidering this, but I realized it could be a breaking change. If other people have already dealt with this by swapping icons and localization, it might break for them. I'm setting this as a goal for v7
