### ISSUE TITLE
promptTimeOnDateChange  option

### ISSUE THREAD

**Issue by usmazat** [Eonasdan/tempus-dominus#2630]
### Discussed in https://github.com/Eonasdan/tempus-dominus/discussions/2618

<div type='discussions-op-text'>

<sup>Originally posted by **usmazat** August  7, 2022</sup>
Hi everyone! I'm not sure if it is a bug, or maybe I'm just missing something super obvious here, but I can't get the promptTimeOnDateChange option to work .I tried  following simple setup using [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-klzcd4?file=index.js), when I select a date, time portion doesn't popup as it supposedly should. Stackblitz console doesn't show anything, but then I use "open in a new window" link and then open chrome (  version 103.0.5060.134) console I see the following stack trace popup after a select a date 
 ```
 actions.ts:173 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at Actions.do (actions.ts:173:35)
    at actions.ts:31:20
    at event-emitter.ts:21:7
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (event-emitter.ts:20:22)
    at tempus-dominus.ts:459:36
do @ actions.ts:173
(анонимная) @ actions.ts:31
(анонимная) @ event-emitter.ts:21
emit @ event-emitter.ts:20
(анонимная) @ tempus-dominus.ts:459
Объект setTimeout (асинхронный)
_handleAfterChangeEvent @ tempus-dominus.ts:457
_triggerEvent @ tempus-dominus.ts:253
(анонимная) @ tempus-dominus.ts:62
(анонимная) @ event-emitter.ts:21
emit @ event-emitter.ts:20
setValue @ dates.ts:250
do @ actions.ts:105
(анонимная) @ actions.ts:31
(анонимная) @ event-emitter.ts:21
emit @ event-emitter.ts:20
Display._actionsClickEvent @ index.ts:758
```
the same thing happens in firefox   (version 103.0.1 (64-bit))

```
Uncaught TypeError: currentTarget is null
    do actions.ts:173
    Actions actions.ts:31
    emit event-emitter.ts:21
    emit event-emitter.ts:20
    _currentPromptTimeTimeout tempus-dominus.ts:459
```
I'm using windows 10 version 21H1. Any Idea what I'm missing here?
The same thing still happens with v6 beta10 (I updated the discussion with correct stackbkitz url) My locale is ru-Ru</div>

**Comment by Eonasdan** [comment]
Hello, please check [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-2720?file=index.js).

**Comment by blankse** [comment]
@Eonasdan I don't see any promptTimeOnDateChange option in this StackBlitz.

**Comment by Eonasdan** [comment]
Oops! Sorry that was the wrong ticket. I just started working on this one.

**Comment by Eonasdan** [comment]
Seriously though, try [this one](https://stackblitz.com/edit/tempus-dominus-2630?file=index.js)

**Comment by blankse** [comment]
@Eonasdan Works for me. Thanks!

**Comment by ActionJONA** [comment]
Found the issue.
Line 3871 of: [JS](https://github.com/Eonasdan/tempus-dominus/blob/master/dist/js/tempus-dominus.js)

Is: 
> currentTarget: this.display.widget.querySelector(`.${Namespace.css.switch} div`),

Should be: 
> currentTarget: this.display.widget.querySelector(`.${Namespace.css.toolbar} div`),
