### ISSUE TITLE
remove debugger command on customDateFormat

### ISSUE THREAD

**Issue by hieplq** [Eonasdan/tempus-dominus#2636]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

please remove debugger command when release code

![image](https://user-images.githubusercontent.com/4666285/185971483-20704354-6dac-4ddf-b0ac-20879eb6781b.png)

### Motivation and context

it busy me when i open developer tool

**Comment by Eonasdan** [comment]
Oops sorry about that. I had a fix in but another npm package randomly disappeared and now github won't build the project. I'll try to get some time to fix this.

**Comment by Eonasdan** [comment]
Done. 6.0.1
