### ISSUE TITLE
Allow support for FloatingUI

### ISSUE THREAD

**Issue by oschleic** [Eonasdan/tempus-dominus#2640]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

Remove the requirement for popperJS and add support for using [FloatingUI](https://floating-ui.com/docs/getting-started). 

I have a partial implementation [here](https://github.com/oschleic/tempus-dominus).

### Motivation and context

I'd like to be able to directly use this library, without the requirement of popperJS. One possible solution would be to make popperJS an optional peer dependency, and allow for custom handling of the "popperInstance" in the implementation. It will allow for more granular control in the implementation while still allowing for default behavior to be implemented using popperJS.   

For more info on migrations see https://floating-ui.com/docs/migration

**Comment by Eonasdan** [comment]
I have looked at floating ui and I do want to move to it at some point. Well bootstrap is no longer a dependency, I'm guessing that's where most people are using it. BS5 moved to popper 2 and they have opened tickets to migrate as well. If I simply migrate now, most people will have yet another dependency.

I would consider a PR that hide the implementation that defaulted to popper but could be overwritten in a plugin to use floating ui or w/e. That's probably the way forward anyway.
