### ISSUE TITLE
Typescript import problems in v6.0.1

### ISSUE THREAD

**Issue by grassick** [Eonasdan/tempus-dominus#2652]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Previous versions of 6.0.0 beta worked in typescript, but in 6.0.1, `Module '"@eonasdan/tempus-dominus"' has no exported member 'TempusDominus'.`

### StackBlitz fork

https://stackblitz.com/edit/v6-typescript-wxnqmy?file=index.ts

But I didn't need to change anything in the fork to get it to error

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.0.1

### What your browser's locale? You can find this information from the sample StackBlitz.

en-GB

**Comment by Eonasdan** [comment]
This should be resolved in the latest version. Sorry about that.
