### ISSUE TITLE
disabledDates causes lateness and next /previous navigation issues

### ISSUE THREAD

**Issue by RamonaBarbieru** [Eonasdan/tempus-dominus#2658]
When disabledDates is loaded with an long array of dates, it causes lateness. For 800 entries it takes around 20 seconds to show (I need 5 year worth of data). The issue is in _isInDisabledDates -> mapping on return statement because for every date shown it reprocesses all disabled dates. 
![DisabledDates](https://user-images.githubusercontent.com/25681687/191241868-b6b8081f-4503-4393-a4ef-6de4c6a4f13c.png)
It would be a very quick fix to solve this, just remember the formatted disabled dates array on the first occurrence.
[disabledDatesArray.txt](https://github.com/Eonasdan/tempus-dominus/files/9607177/disabledDatesArray.txt)

Another issue, also tied with disabled dates is that I cannot navigate next/previous month for all months.

I attached a file with dates that can be passed for testing.

**Comment by Eonasdan** [comment]
Hi please check this branch https://github.com/Eonasdan/tempus-dominus/tree/2658-disableddates-causes-lateness-and-next-previous-navigation-issues.

Also.. I hope you aren't actually building a list of every single weekend cause there's an option to disable days of the week.

**Comment by Eonasdan** [comment]
Here's a [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-2658) of this working

**Comment by Eonasdan** [comment]
Awesome. I'll get this merged soon

**Comment by Eonasdan** [comment]
This was released with 6.2.6
