### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to resolve module specifier '@popperjs/core'

### ISSUE THREAD

**Issue by pramodboda** [Eonasdan/tempus-dominus#2664]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Uncaught (in promise) TypeError: Failed to resolve module specifier '@popperjs/core'

When we click on datepicker or timepicker, Calendar UI is not showing at targeted place. 
Even we have this issue in your website: https://getdatepicker.com/6/functions/dates.html

### StackBlitz fork

https://stackblitz.com/edit/web-platform-1svl7a?file=index.html,script.js

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of are you using? You can find this information from the sample StackBlitz.

v6.1.2

### What your browser's locale? You can find this information from the sample StackBlitz.

en

**Comment by faridjame** [comment]
This is the exact issue I'm experiencing as well. Here is the line that's erroring out: 

`  
async createPopup(element: HTMLElement, widget: HTMLElement, options: any): Promise<void>  {
    const { createPopper } = await import('@popperjs/core'); //ERROR
    this._popperInstance = createPopper(element, widget, options);
}
`

**Comment by oschleic** [comment]
This will be fixed by #2663, in the meantime changing your version to ^6.0.0 should fix it

**Comment by Eonasdan** [comment]
This is resolved in 6.2.3
