### ISSUE TITLE
Namespace.errorMessages.numbersOutOfRage is misspelled

### ISSUE THREAD

**Issue by m-gallesio** [Eonasdan/tempus-dominus#2667]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

The method `Namespace.errorMessages.numbersOutOfRage` has a misspelled name, it should be `numbersOutOfRange`.
This method is public, so technically this would be a breaking change.

### StackBlitz fork

Not applicable, see code at https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/utilities/errors.ts#L79

### What version of are you using? You can find this information from the sample StackBlitz.

6.1.2

**Comment by Eonasdan** [comment]
fixed in 6.2.4. thanks
