### ISSUE TITLE
Tag name for 6.1.3 is wrong

### ISSUE THREAD

**Issue by m-gallesio** [Eonasdan/tempus-dominus#2670]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

The current release has been tagged as 6.2.3 but its actual version number is 6.1.3

**Comment by Eonasdan** [comment]
fixed some other stuff v6.2.4 is out. thanks
