### ISSUE TITLE
Move back @popperjs/core to peerDependencies

### ISSUE THREAD

**Issue by m-gallesio** [Eonasdan/tempus-dominus#2672]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

During work for https://github.com/Eonasdan/tempus-dominus/issues/2640 `@popperjs/core` was moved from a peer dependency to an optional dependency due to the possibility of specifying a custom popup implementation.
However in order to skip Popper `@popperjs/core` while installing npm packages this mandates always including the `--no-optional` flag which creates reproducibility problems if `package-lock` is not persisted.
I think moving it back to peerDependencies + optional flag would fix the issue.

See this old npm issue for reference: https://github.com/npm/npm/issues/14185

**Comment by Eonasdan** [comment]
" peerDependencies + optional flag" I get the peer bit but what would the optional flag look like?

**Comment by m-gallesio** [comment]
I do not know if a "peer + optional" mode exists, but just declaring it as a peer dependency should work, I think.
This obviously means `@popperjs/core` would have to be installed manually (like older versions of bootstrap-datetimepicker required bootstrap as a peer dependency).

**Comment by oschleic** [comment]
What about https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta
