### ISSUE TITLE
Text parsing of the Date (if typed) fails

### ISSUE THREAD

**Issue by PaulFarry** [Eonasdan/tempus-dominus#2678]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

If the user Types into the Date Field and the format is that same as Simple (https://getdatepicker.com/6/repl.html), then if they happen to remove the (Space) between the Time and the Am/Pm then the application fails to run.

Error: TD: Could not correctly parse "03/10/2022, 7:30pm" to a date for input.
    TdError tempus-dominus.js:470
    failedToParseDate errors.ts:122
    dateConversion optionConverter.ts:538
    parseInput dates.ts:86

If I correct the space then it parses successfully.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-repl?embed=1&file=index.html%2Cexample.js&hideNavigation=1

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en-AU

**Comment by Eonasdan** [comment]
Unfortunately, this is the nature of the Intl native javascript parser. You could either use the custom format plugin or check the momentjs plugin
