### ISSUE TITLE
Plugin fa_five is not a function

### ISSUE THREAD

**Issue by Jashtoyunda** [Eonasdan/tempus-dominus#2681]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I updated TempusDominus from 6.0.0-beta4 to the latest version (6.2.4), and the loading of the `fa_five` plugin (Font Awesome 5) crashes : 

`Uncaught TypeError: plugin is not a function
    extend tempus-dominus.ts:555`

The line in question is : 
`tempusDominus.extend(window.tempusDominus.plugins.fa_five);`

The problem is, `window.tempusDominus.plugins.fa_five` returns an `Object`, and not a `function` (in comparison, plugin `moment_parse` is fine).

The issue can't be reproduced on StackBlitz, plugins do not seem available on it.

### StackBlitz fork

The issue can't be reproduced on StackBlitz, plugins do not seem available on it.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.4

### What your browser's locale? You can find this information from the sample StackBlitz.

fr

**Comment by Eonasdan** [comment]
Please update to the latest version of the picker and test again. If you still have the issue, please provide a stackblitz example
