### ISSUE TITLE
Modifying date display in calendar

### ISSUE THREAD

**Issue by jasonmonroe** [Eonasdan/tempus-dominus#2682]
### Discussed in https://github.com/Eonasdan/tempus-dominus/discussions/2642

<div type='discussions-op-text'>

<sup>Originally posted by **jasonmonroe** August 30, 2022</sup>
How can we modify the datepicker date display values on the calendar? Right now my month is "August 22" but I want "August 2022".  Also, the days are displayed as  "Mon, Tue, Wed".. but I want "Mo, Tu, We". I'm using Tempus Dominus v6. Please advise. Thanks.

Note: I also posted this comment in another thread but realized they were asking something similar but different from what I want.</div>

**Comment by jasonmonroe** [comment]
dayViewHeaderFormat: { month: 'long', year: '2-digit' },  I need 4 Digits.  I also need Weekdays in two character format, not three.

**Comment by Eonasdan** [comment]
There's no way to modify the week headers. You can use `dayViewHeaderFormat: { month: 'long', year: 'numeric' },` for the four digit year
