### ISSUE TITLE
Month freeze in side by side view

### ISSUE THREAD

**Issue by AlexandreMcCune** [Eonasdan/tempus-dominus#2685]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

With a side by side datetime picker, the month freeze after using the time picker

Step-by-step to replicate the bug:

- Open the datetime picker
- Click on the hour or minute number and select  a value
- Use the arrows to change month.

At that point, the month do not change.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-pphjdf?embed=1&file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en-CA

**Comment by Eonasdan** [comment]
Hi this should be fixed in the related branch, please check this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-2685?file=index.js)

**Comment by Eonasdan** [comment]
Hello. This should be fixed in 6.2.7
