### ISSUE TITLE
Provide a way to switch back to default (en) locale

### ISSUE THREAD

**Issue by m-gallesio** [Eonasdan/tempus-dominus#2687]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

I think there should be a way to explicitly set the locale of a single picker to the library default (en / en-US), which does not seem possible at the moment.

### Motivation and context

This is relevant in the following cases:
- the global locale is overridden
- there is a desire to keep the code "culture-neutral", so the locale is explicitly set every time

**Comment by Eonasdan** [comment]
I don't follow. The locale can be set per picker or globally and the `updateOptions` would give you the ability to change it whenever you needed.

**Comment by m-gallesio** [comment]
Take this code:
```typescript
import { TempusDominus, loadLocale, locale } from '@eonasdan/tempus-dominus';
import { localization, name } from "@eonasdan/tempus-dominus/dist/locales/it";
loadLocale({localization, name});
locale('it');

const td = new TempusDominus(document.getElementById('datetimepicker1'));
```
Now that the global locale is `it`, there does not seem to be an immediate way to set a single picker to *specifically* an `en`/`en-us` locale.
This also conceptually happens if the browser's current locale is something other than `en`/`en-us` (it starts with a language other than English).

**Comment by Eonasdan** [comment]
Can do `td = new TempusDominus(document.getElementById('datetimepicker1'), { localization: { locale: 'en' }})`

**Comment by m-gallesio** [comment]
That does change the displayed language in the main picker (which I assume uses `Intl`) but not the tooltips and some other options (e.g. first day of the week).

**Comment by Eonasdan** [comment]
OOH. I see. Since you said locale, I thought you where talking about `localization.locale` not the localization object itself.

Right so setting it globally replaces the defaultoptions and thus there is no way to revert that. Hmm. I could create an en-Us locale file that could be loaded. That seems heavy though.

![HeavyGIF](https://user-images.githubusercontent.com/1006516/197896268-369dc1ff-aacb-4eac-9918-afa16033f910.gif)

**Comment by m-gallesio** [comment]
Update, I tried doing this at startup (no global TD locale, browser in `it` locale):
```typescript
loadLocale({ localization: DefaultOptions.localization, name: "en-us" });
```
which partially works since it sets tooltips and day of week, but not those parts which depend on `Intl`:

![immagine](https://user-images.githubusercontent.com/46478501/197966303-07e9f81e-4d03-4cd0-9e09-eb7a6c288283.png)

I also anticipate the need of an `en-gb` locale due to differing date formats, unless it can be somehow managed with `Intl`.

**Comment by mvxproject** [comment]
To set locale globally to English:  

` tempusDominus.DefaultOptions.localization.locale = 'en';`

To test:  

Open DevTools in Chrome -> Open the Console drawer. Click on the three-dotted menu -> Click on More tools -> Sensors. From the Sensors tab, set the location according to your preference.

Before:

![before](https://user-images.githubusercontent.com/14152349/199779821-a78c8c37-bf1c-44a2-ac7e-12b689fba130.png)


after setting :  ` tempusDominus.DefaultOptions.localization.locale = 'en';`

![after](https://user-images.githubusercontent.com/14152349/199780003-796454fd-31e0-4e27-8503-38c904f1657d.png)

I have to mention one problem with localization when using CustomDateFormat plugin: 

the meridian am pm, are always used even in cultures like 'fr' 

![fr](https://user-images.githubusercontent.com/14152349/199781797-efc67b5c-c110-4be0-a4d9-ab36187a0b8b.png)

**Comment by Eonasdan** [comment]
Hello 6.7.7 should resolve this. There's an additional export `DefaultEnLocalization` that provides the default en-US locale options
