### ISSUE TITLE
Options type is removed from the exported types, but is still a public api (constructor of TempusDominus)

### ISSUE THREAD

**Issue by jcompagner** [Eonasdan/tempus-dominus#2688]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

please bring back in the export also "Options"

### Motivation and context

see:

https://github.com/Eonasdan/tempus-dominus/blob/master/types/tempus-dominus.d.ts#L22

and

https://github.com/Eonasdan/tempus-dominus/blob/master/types/tempus-dominus.d.ts#L162

that last line had before also Options so i could use that type also in my code to be sure i have the correct object (the naming and so on)

But now the Options type is removed it seems.  But it is still used in public api and is very handy to use.

**Comment by Eonasdan** [comment]
Hi please check 6.2.5
