### ISSUE TITLE
customDateFormat shows 'undefined' when you manually erase the date

### ISSUE THREAD

**Issue by Frenzie** [Eonasdan/tempus-dominus#2693]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

See the sample on https://getdatepicker.com/6/plugins/customDateFormat.html

#### Steps to reproduce

1. Set a date
2. Empty the input
3. The input now shows 'undefined'
![image](https://user-images.githubusercontent.com/202757/197183641-c633aac1-11b3-476e-b673-f7be819b5e8f.png)

#### Expected

It's just empty.

### StackBlitz fork

https://getdatepicker.com/6/plugins/customDateFormat.html

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by JerryBels** [comment]
Came here to report exactly that... +1

**Comment by dcopadosalmeron** [comment]
By default, the "defaultDate" option is equal to undefined. Just set this option to double quotes: defaultDate: ""
[doc](https://getdatepicker.com/6/options/)

**Comment by Frenzie** [comment]
An empty or random string doesn't seem to be accepted. At a glance only an ISO string or a Date object are accepted.

But luckily `defaultDate` doesn't affect the steps described regardless. If it did you could just replace `undefined` in my OP with `defaultDate`. ;-)

The correct behavior is observed when you click the trashcan from adding `clear: true` and when customDateFormat isn't enabled:
```
    buttons:{
      clear: true
    },
```

**Comment by JerryBels** [comment]
Yes I can confirm `defaultDate` doesn't have anything to do with the matter.

**Comment by Frenzie** [comment]
I don't think I understand the other changes but the `if (!date) return ''` part seems to have the intended effect. :+1:

**Comment by Eonasdan** [comment]
Yeah I'm still trying to get the plugin to behave with time zone bits and thought I could squeeze it in. Glad it's working, I'll get it pub'd soon.

**Comment by Eonasdan** [comment]
Hello. This should be fixed in 6.2.7
