### ISSUE TITLE
Prevent Navbar dropdown being obscured in 'inline' mode

### ISSUE THREAD

**Issue by dleffler** [Eonasdan/tempus-dominus#2697]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

Add the following to tempus-dominus.scss for the class 'inline' around line 138

```
    &.inline {
      z-index: inherit;
    }

### Motivation and context

I have used 'inline' mode quite often and this simple fix helps me.

**Comment by Eonasdan** [comment]
I don't have enough information to help you. If you can provide screenshots or a stackblitz example, I can take another look.
