### ISSUE TITLE
Some examples currently broken and others using older version

### ISSUE THREAD

**Issue by cwolcott** [Eonasdan/tempus-dominus#2702]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Several of the examples are currently broken:
- Enabled/Disabled Dates
- Parent Container

All other examples are working, but are using version 6.2.4 instead of the lateat

### StackBlitz fork

Looking at your [REPL](https://getdatepicker.com/6/repl.html) page

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.6

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Thanks. Should be updated now

**Comment by cwolcott** [comment]
@Eonasdan I see that you upgraded the examples to 6.2.6 (Thanks), but two examples are still broken.

- Enabled/Disabled Dates
- Parent Container
