### ISSUE TITLE
getdatepicker.com still links to the old docs, but calls it "latest"

### ISSUE THREAD

**Issue by guettli** [Eonasdan/tempus-dominus#2706]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

https://getdatepicker.com/

![image](https://user-images.githubusercontent.com/414336/199278332-ee30d5bd-261b-41bf-a06f-16f4462340db.png)

### StackBlitz fork

.

### What operating system(s) are you seeing the problem on?

Linux

### What version of are you using? You can find this information from the sample StackBlitz.

6.2

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by guettli** [comment]
The docs are outdated. 

Related answer: https://github.com/Eonasdan/tempus-dominus/discussions/2704#discussioncomment-4029254

**Comment by Eonasdan** [comment]
Hello. This should be fixed in 6.2.7
