### ISSUE TITLE
Data ranges

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2707]
### Discussed in https://github.com/Eonasdan/tempus-dominus/discussions/2382

<div type='discussions-op-text'>

<sup>Originally posted by **tiagocaus** August 24, 2021</sup>
How do I create quick options with dates?

Sample image: https://prnt.sc/1qhcogh

Thanks</div>

**Comment by martinapitakova** [comment]
Hi @Eonasdan ,

I need this in my project. I see that you moved it to **Ready** state. Please, can you provide me approximate date, when this will be implemented?

Thanks.

**Comment by Eonasdan** [comment]
Hopefully, soon. You can use linked pickers meanwhile, or you could handle it with multidate setup.

**Comment by Eonasdan** [comment]
Still some CSS issues to work out, but it's working 
![image](https://user-images.githubusercontent.com/1006516/223301005-8f236768-1dcf-4ed5-944f-f468411731ed.png)

![image](https://user-images.githubusercontent.com/1006516/223301073-27199d81-2e7d-4e54-bdf7-7e785006d44d.png)

**Comment by Eonasdan** [comment]
This is going out in the next release.

Use

```
{
    dateRange: true,
    multipleDatesSeparator: '-',
}
```
