### ISSUE TITLE
Make "State of my Picker" blog post available again

### ISSUE THREAD

**Issue by guettli** [Eonasdan/tempus-dominus#2708]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

https://eonasdan.com/state-of-my-picker

The above link is not reachable (at least not for me yesterday, and today).

### Motivation and context

I would like to read the blog post.

**Comment by Eonasdan** [comment]
Huh. Looks like the redirect failed 😢 .

There's a couple of blog posts related to the picker here https://jonathanpeterson.com/

Where did you find the link to that?

**Comment by guettli** [comment]
@Eonasdan I found the link here: https://getdatepicker.com/5-4/Installing/

**Comment by Eonasdan** [comment]
Thanks. The old docs have been updated.
