### ISSUE TITLE
Bootstrap Icons plugin

### ISSUE THREAD

**Issue by mvxproject** [Eonasdan/tempus-dominus#2709]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

Like fa-five plugin we can use a plugin for Bootstrap Icons :

[bootstrap-icons.txt](https://github.com/Eonasdan/tempus-dominus/files/9922491/bootstrap-icons.txt)

and to use it:

`tempusDominus.extend(window.tempusDominus.plugins.bootstrap_icons.load);`

### Motivation and context

If your are using Bootstrap and Bootstrap Icons, this plugin will be useful.

**Comment by Eonasdan** [comment]
Hi, this was created recently: https://getdatepicker.com/6/plugins/bi1.html

Closing as completed
