### ISSUE TITLE
Give Option To Remove The Extra Row of Dates

### ISSUE THREAD

**Issue by r-debashis** [Eonasdan/tempus-dominus#2717]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

The current implementation shows an extra row of dates in calendar mode as shown in the image below.
We need an option to remove that. In many cases, it does not look good, and for mobile it occupies some extra space.
Add an option like "restrictToFiveRows" for the calendar mode. That should keep things backwards compatible also.

![tempus-dominus-bug](https://user-images.githubusercontent.com/17682511/200416501-57581a49-8238-44db-b86b-51579a91c38a.png)

### Motivation and context

This should help people who are working with restricted screen area, or need that screen area for other purposes.

**Comment by Eonasdan** [comment]
The picker will show 42 days. This helps for months at, like November have a partial week. There's only going to be a few cases where there's a complete week is on display that doesn't belong to the month.

**Comment by r-debashis** [comment]
It should be possible to calculate the number of rows required.
But, I guess it's ok if it is too much work.

**Comment by Eonasdan** [comment]
The main issue is that it would shift around depending on the month. The material design calendar shows 5 rows as well. You could hide the `old` and `new` if you wanted or change the font color so it doesn't display.

I'm going to close this ticket as I don't think I really want to focus on it. Hope you understand. Thanks for using my picker
