### ISSUE TITLE
Locales are not properly importable in Typescript

### ISSUE THREAD

**Issue by Thodor12** [Eonasdan/tempus-dominus#2719]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

According to the documentation for Typescript you simply have to import the locale files directly, but Typescript is throwing errors about missing declaration files, whilst this does not immediately inhibit runtime functionality, it should also not throw errors and just provide the typings correctly.

### StackBlitz fork

https://stackblitz.com/edit/v6-typescript-d6rf8f?file=index.ts

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.7

### What your browser's locale? You can find this information from the sample StackBlitz.

nl-NL

**Comment by Eonasdan** [comment]
Hi. I think I fixed this in the attached branch. I created a SB for this but I think the cache is behind (at least for me) https://stackblitz.com/edit/typescript-y2nxnt?file=index.ts. If you can test it from the branch, great. If not, I'll probably just merge the changes in and verify after a version bump.
