### ISSUE TITLE
Error when using clear button on time component

### ISSUE THREAD

**Issue by depape** [Eonasdan/tempus-dominus#2720]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When I use clear button on clock only component input field gets cleared, but it displays following error:

Uncaught TypeError: Cannot read properties of null (reading 'classList')

I am using following configuration:

new TempusDominus(document.getElementById('datetimepicker1'), {
  display: {
    viewMode: 'clock',
    components: {
      decades: false,
      year: false,
      month: false,
      date: false,
      hours: true,
      minutes: true,
      seconds: false,
    },
    buttons: {
      close: true,
      clear: true,
    },
  },
});

Seems like same error happens on your example page:

![time-error](https://user-images.githubusercontent.com/13101092/202109287-91c4461f-dec0-461d-8953-17285af94ca4.jpg)

### StackBlitz fork

https://tempus-dominus-v6-next-ilzxk9.stackblitz.io

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.7

### What your browser's locale? You can find this information from the sample StackBlitz.

sl-SI

**Comment by Eonasdan** [comment]
Hello, please check [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-2720?file=index.js).

**Comment by depape** [comment]
Thanks, error is gone now!

**Comment by Eonasdan** [comment]
Awesome. This will be release soon
