### ISSUE TITLE
Tempus Dominus v6 clear button not working

### ISSUE THREAD

**Issue by ayoubaitouhmad** [Eonasdan/tempus-dominus#2722]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Tempus Dominus v6 clear button not working
![date](https://user-images.githubusercontent.com/70922934/203280303-125bc775-d5d9-4a0e-8087-ad5b384cfa36.PNG)

### StackBlitz fork

![date](https://user-images.githubusercontent.com/70922934/203280776-5f458b41-fc24-4c1e-b63a-56766ce21a11.PNG)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6

### What your browser's locale? You can find this information from the sample StackBlitz.

fr-fr

**Comment by Eonasdan** [comment]
This works for me on the stackblitz link. Do you have any errors or additional details that might help?

**Comment by oprocopio** [comment]
Hi there,

I have a similar issue with version 6.7.13.
If I click on the clear button the current date is set.

**Comment by Eonasdan** [comment]
@oprocopio please create your own issue and provide a stackblitz showing your issue
