### ISSUE TITLE
Uncaught Error: TD: No element was provided.

### ISSUE THREAD

**Issue by wpre** [Eonasdan/tempus-dominus#2723]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I load tempus-dominus.min.js in my wordperss theme. If the page has a datepicker everything works fine. If there is no datepicker on the page, I see this error in the browser console: 

Uncaught Error: TD: No element was provided.
    at Object.mustProvideElement (tempus-dominus.min.js?ver=1.0.4:6:7856)
    at new Y (tempus-dominus.min.js?ver=1.0.4:6:61850)
    at tempus-dominus.min.js?ver=1.0.4:8:1

Any ideas?

### StackBlitz fork

n/a

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.7

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Loading the picker code wouldn't cause this. This error is from you calling the constructor e.g. `var dp = new tempusDominus....` without a valid element.

I would need more information to help you troubleshoot your issue.

**Comment by Eonasdan** [comment]
Are you sure that element exists when the constructor is called? Can you create an example with the StackBlitz example?

**Comment by alit990** [comment]
I have this error on Console too.
