### ISSUE TITLE
Day and month are switched on manual input

### ISSUE THREAD

**Issue by bas-jansen** [Eonasdan/tempus-dominus#2727]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When using manual input, the day and month get switched

Reproducible on https://getdatepicker.com/6/repl.html on multiple computers

Windows settings: 
Language: English (United States)
Region: Netherlands
Regional Format: English (Europe) 

![image](https://user-images.githubusercontent.com/9952186/205911819-2707c075-691a-4c22-bb3c-7d4385d7a353.png)

1. Open the calendar
2. Pick a date (e.g. 7 December: 07/12/2022 13:13)
3. Change the month in the input field from 12 to 11 (07/11/2022 13:13) and click somewhere on the dialog without performing an action (e.g. on a name of a day) 
4. Expected selected date: 7 November
5. Actual: selected date is 11 July. Also in the input field day and month are switched: 11/07/2022 13:13

Additional:
When changing the Regional Format to "English (United States)" it works correctly

### StackBlitz fork

https://tempus-dominus-v6-simple-setup-6fwhut.stackblitz.io/

Just a fork of the default HTML, no edits done

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.7

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
In javascript if you create a data e.g. `new Date('07/12/2022')` the date will be July 11, 2022. The old date picker used momentjs to attempt to handle formats that where not `en-US` format. In order reduce the external dependencies (and momentjs is no longer being updated), I opted to make use of the native JS date object and Intl. However, neither of those support providing custom format parsing. There are ways to provide custom parsing on your own or use the customDateFormat plugin.

That plugin might be rolling into the main picker but I haven't had time to do that.
