### ISSUE TITLE
day in view is not selected when viewDate changed

### ISSUE THREAD

**Issue by lvqthuong** [Eonasdan/tempus-dominus#2735]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

As it's described in the [doc](https://getdatepicker.com/6/functions/dates.html#viewDate),when assigned a new value, view will be refreshed month and year header will be changed correctly to input's value but the day of input's value will not be selected in view.

I've tried dates.setValue() but it will reset the caret position of the input which is annoying to deal with

### StackBlitz fork

https://stackblitz.com/edit/v6-typescript-56v3ie?file=index.ts

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.7

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Hi can you please explain what your code is supposed to be doing?

**Comment by lvqthuong** [comment]
Hi, I'm trying to change a selected day in date view according to what i'm typing in the input field

**Comment by Eonasdan** [comment]
That seemed to work for me. I am stilling for **`change`** event and not key events. If the picker is open and you type a value in the textbox it will not get updated until a change event is fired (input loses focus).

There is plans for key bindings in the future but that needs careful though
