### ISSUE TITLE
Localization hh:mm T not working

### ISSUE THREAD

**Issue by GreggGreen** [Eonasdan/tempus-dominus#2744]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

This used to work on a time field and now it doesn't. The hh for hour says undefined:(. It works with h.

            localization: {
                format: 'hh:mm T',
            },

### StackBlitz fork

It doesn't work.
I'm using customDateFormat so I can't figure out how to put it into StackBlitz

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.9

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
This works for me. I tried in both FF and Chrome. Please see this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-plugins?file=index.html,index.js)

**Comment by GreggGreen** [comment]
I think its working now. Thanks
