### ISSUE TITLE
Intl.LocaleHourCycleKey not defined before ES2020

### ISSUE THREAD

**Issue by m-gallesio** [Eonasdan/tempus-dominus#2745]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

After installing 6.2.9, our TypeScript compilation started to fail with the following message:

```
[...]/node_modules/.pnpm/@eonasdan+tempus-dominus@6.2.9/node_modules/@eonasdan/tempus-dominus/types/tempus-dominus.d.ts(286,20):
error TS2694: Namespace 'Intl' has no exported member 'LocaleHourCycleKey'.
```

This is because `Intl.LocaleHourCycleKey` is new to ES2020 (TypeScript library `lib.es2020.intl.d.ts`) and our project uses ES2016 as a target in `tsconfig.json`.
Overall this seems a relatively recent functionality (2019-2020, see https://caniuse.com/?search=hourCycle). I do not know whether the library actually uses these functionalities or they are just used as a shortcut in the typings, but I fear this might break some older browsers.
Then again this might be fixable with more transpilation steps.

### What version of are you using? You can find this information from the sample StackBlitz.

6,2,9

### What your browser's locale? You can find this information from the sample StackBlitz.

it-IT

**Comment by Eonasdan** [comment]
Unfortunately, I don't think I'm going to do anything about this right now. `LocaleHourCycleKey` is a typing for the following values: `"h12" | "h23" | "h11" | "h24"`. 

Sorry for the inconvenience.

**Comment by m-gallesio** [comment]
After some testing I have found any of these two solutions to work:

1. Add `ES2020.Intl` to `lib` in `tsconfig.json`.
2. Explicitly extend `Intl` by copying the relevant type definition somewhere in the declarations:
```typescript
module Intl {
    export type LocaleHourCycleKey = "h12" | "h23" | "h11" | "h24";
}
```

This does not seem to require further action.
