### ISSUE TITLE
Cant change time & meridiem on latest version 6.2.9

### ISSUE THREAD

**Issue by luncan987** [Eonasdan/tempus-dominus#2746]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When using 12 clock mode, there is an error on clock change (time & pm/am) click 

`Error in /turbo_modules/@eonasdan/tempus-dominus@6.2.9/dist/js/tempus-dominus.js (1959:62)
Cannot read properties of undefined (reading 'parentElement') `

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-import-vyva8r?file=index.js

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.9

### What your browser's locale? You can find this information from the sample StackBlitz.

en-gb

**Comment by luncan987** [comment]
it works fine when the calender attribute set to true on display.components object.

**Comment by Eonasdan** [comment]
Please check 6.2.10
