### ISSUE TITLE
Unnecessary suffix "日" to the date part of the calendar for locate "ja"

### ISSUE THREAD

**Issue by vuninhhiep** [Eonasdan/tempus-dominus#2750]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

hi @Eonasdan please have a look at https://codepen.io/vuninhhiep/pen/YzjWaQx, you can see "日" after each date of the month

### StackBlitz fork

https://codepen.io/vuninhhiep/pen/YzjWaQx

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

en

**Comment by Eonasdan** [comment]
Hi this should be fixed in the next release
