### ISSUE TITLE
Clicking on toggle meridiem button causes focus to change.

### ISSUE THREAD

**Issue by 2gen** [Eonasdan/tempus-dominus#2752]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When clicking the toggle meridiem button on the time picker within an extra long Bootstrap modal the focus is changed to the first focusable element in the modal which will cause the viewport to jump up to the focusable element.

### StackBlitz fork

https://tempus-dominus-v6-simple-setup-3p9m9w.stackblitz.io

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

en

**Comment by Eonasdan** [comment]
That's strange and oddly specific, lol. I'll try to see if I can track this down.

**Comment by Eonasdan** [comment]
This is probably related to popper. You might have better luck with using floating ui. There's a plugin for that.
