### ISSUE TITLE
auto-complete on keyboard-input

### ISSUE THREAD

**Issue by KlueberAl** [Eonasdan/tempus-dominus#2753]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

In the case of keyboard input, where only part of the information is entered, the rest should be completed with the current data, when the input field is exited.

Even if it was not intended, it worked in some cases already in Tempus-Dominus 5. For example for a pure date field and German format. Today is 18 January 2023, If you enter 25 and leave the field, the ".01.2023" is automatically added for the current month and year:
[https://stackblitz.com/edit/v5-4-minimum-setup-jk5kvx?file=index.js](https://stackblitz.com/edit/v5-4-minimum-setup-jk5kvx?file=index.js)

Unfortunately, this no longer works in Tempus Dominus 6. No date object is created at all anymore.

### Motivation and context

This is a very useful feature for end users who only use keyboard input. These users would only have to enter the minimum amount of data needed to generate a correct date. This simplified the input immensely.

I would find this featuere very great. Thank you very much for your great work.

**Comment by Eonasdan** [comment]
The reason v5 did that was probably momentjs, which is no longer used or supported. This wouldn't be a big priority for me right now but I'll leave it open as a feature request.
