### ISSUE TITLE
no date-object by keyboard input or given value-tag on localized datepicker

### ISSUE THREAD

**Issue by KlueberAl** [Eonasdan/tempus-dominus#2754]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

If the datepicker is defined for localized date formats and a) you enter a date from the keyboard or b) you have specified the date in the value-tag, this will result in an error (no date object).

Thanks for helping!

### StackBlitz fork

[not working example v6](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-iee7x7?file=index.html,index.js)

[working example v5](https://stackblitz.com/edit/v5-4-minimum-setup-8nur6i?file=index.html,index.js)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

de

**Comment by Eonasdan** [comment]
Until #2756 is merged, you will have to use the [custom date forms plugin](https://getdatepicker.com/6/plugins/customDateFormat.html).

I hope to get this merged soon, however.
