### ISSUE TITLE
first row gets missed on specific locale

### ISSUE THREAD

**Issue by tirolel** [Eonasdan/tempus-dominus#2757]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

While testing our web application, we find out that if we set start of the week, the first row gets missing. I have already searched duplicates/closed issues, and I came accross this one, which #2537 is almost same issue but it seems its closed and fixed (?)

In the documentation, https://getdatepicker.com/6/options/localization.html#startOfTheWeek, it says there is no apis to get locales start of the week. I'am not sure, but I think we can obtain the first day of week, by doing following:
  
`const firstDayOfWeek = new Intl.Locale(locale).weekInfo.firstDay; `

But let say if use 'ar-iq' as locale, and get the firstDayOfWeek, from Intl Api, so saturday is first day of week (6).
As per example, the first row gets hidden/removed.

I found out that, same issue exist on indian, "hi-hi" locale.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-ghennc?file=index.js

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

Latest, 6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

da-DK / en-gb

**Comment by Eonasdan** [comment]
This appears to be a bug in the logic that attempts to figure out what the first week should look like based on the `startOfTheWeek`. This isn't really a locale issue, since it does something similar with `en-us`.

 According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo) and CanIUse `weekInfo` isn't available on FF-based browsers, which unfortunately means I can't use that to "guess".

**Comment by Eonasdan** [comment]
Hi, please check [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-2757-start-of-the-week?file=index.js,index.html).

**Comment by tirolel** [comment]
Thank you, It looks great!

**Comment by Eonasdan** [comment]
This has been released
