### ISSUE TITLE
Leading delimiter added when multipleDates: true

### ISSUE THREAD

**Issue by e2718281** [Eonasdan/tempus-dominus#2766]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When multipleDates: true and all dates are deselected, subsequently reselecting dates inserts a leading delimiter:

"; 02/21/2023, 7:33 PM; 02/22/2023, 7:33 PM"

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-4kmytj?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
This should be fixed now
