### ISSUE TITLE
when 'value' attribute set on <input> tag, the datepicker defaults to the day prior.

### ISSUE THREAD

**Issue by e2718281** [Eonasdan/tempus-dominus#2767]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

For example, when the following html tag is generated:

<input type="text" name="foo" value="2023-12-02" class="datepicker dateinput form-control" required="" id="id_foo">

...the initial field value appears as 12/01/2023 (?index error; see StackBlitz)

![Capture2](https://user-images.githubusercontent.com/26353036/221927823-bc09b705-3873-45a9-a659-5d212fbd1083.JPG)
![Capture1](https://user-images.githubusercontent.com/26353036/221927825-14ca18a8-57ff-4192-8588-e96a51932f55.JPG)

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-a9i5rq?file=index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
JS doesn't parse partial ISO strings correctly. Without the time portion JS will parse it like this:

```js
new Date('2023-12-31')
> Sat Dec 30 2023 19:00:00 GMT-0500 (Eastern Standard Time)
```
You'll need to adjust the [`localization.format`](https://getdatepicker.com/6/options/localization.html#format) option
