### ISSUE TITLE
[Bug]Time widget does not kept the time if the time is manually entered

### ISSUE THREAD

**Issue by lenamtl** [Eonasdan/tempus-dominus#2770]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Hi,

Here is a demo of the time picker standalone
https://jsfiddle.net/lenamtl/bh6dgLkv/

The actual settings:
- time only 
- 24h format
- be able to enter the time manually and use the widget by clicking the input or a button

Problem:
Time entered manually into the input is not kept when editing using the widget.

To reproduce
Enter any time manually let say 18:00
Open the time picker widget (using a button or by clicking on the input) is not diplaying 18:00 and it should be.
It display actual time instead of displaying 18:00

Note : I have tested the same case with date using the calendar widget and it kept the manually entered date.
So it should do the same for time.
This is standard, this is what does every time and date plugin.

This issue is the main reason why I'm not using this plugin and I hope this is going to be fixed soon.

*Any temporary solution is welcome

Thanks

### StackBlitz fork

https://jsfiddle.net/lenamtl/bh6dgLkv/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

the latest

### What your browser's locale? You can find this information from the sample StackBlitz.

en-us

**Comment by Eonasdan** [comment]
You'll notice that on your fiddle, that there's a warning on the console that `useTwentyFour` is deprecated.

Please update your config to include:

```js
localization: {
    hourCycle: 'h23',
    format:'HH:mm'
 }
```
