### ISSUE TITLE
Format issue in version 6.4

### ISSUE THREAD

**Issue by rhousham** [Eonasdan/tempus-dominus#2778]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Using the format dd-MMM-yyyy doesn't seem to work - it did before in 6.2 using the customFormatJs
Please see the Blitz fork.
https://tempus-dominus-v6-simple-setup-abycvg.stackblitz.io

### StackBlitz fork

https://tempus-dominus-v6-simple-setup-abycvg.stackblitz.io

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en-gb

**Comment by edi-monefy** [comment]
It seems that custom display / formatting is broken altogether in the new version. I'm using the following options to hide the time, but it's still showing up.

`{
    display: {
      components: {
        calendar: true,
        date: true,
        month: true,
        year: true,
        decades: true,
        clock: false,
        hours: false,
        minutes: false,
        seconds: false,
      },
    }
}`

**Comment by Eonasdan** [comment]
Hello, this should be fixed with 6.4.3

**Comment by Eonasdan** [comment]
@edi-monefy I don't see your issue, please try this on stackblitz and open a separate issue if needed.
