### ISSUE TITLE
Format issue with version 6.4.4

### ISSUE THREAD

**Issue by chrisskalog** [Eonasdan/tempus-dominus#2781]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

We use the el-GR locale when instanciating a datetime control but is is ignored
For example it shows 03/22/2023 4:05 Μ.Μ when the proper value should be 22/03/2023 16:05:22

In version 6.2.* it worked fine

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-oczy3u?file=index.js,index.html

### What operating system(s) are you seeing the problem on?

Windows, Android

### What version of are you using? You can find this information from the sample StackBlitz.

6.4.4

### What your browser's locale? You can find this information from the sample StackBlitz.

el, en-GB both have the same problem

**Comment by luncan987** [comment]
apparently for some reason, newer verison (^6.2.10), has some issues with changing locale "on the go". 6.4.4 fixes the issue but the date format gets "messed up"

**Comment by cwolcott** [comment]
I think this is a similar issue.  All I did is upgrade from 6.2.7 to 6.4.4 and am receiving:
   **_Uncaught Error: TD: customDateFormat: Unable to parse provided input: 2022-03-19 00:00:00, format: L LT_**

I tried a couple other versions and everything worked in 6.2.10, but broke for the first time in 6.4.1.

Base on the stack trace it is occurring in my code when I:
`_detailsEndDatePicker.dates.setFromInput(notebookDetails['END_DATE'] + ' 00:00:00');_`

**Comment by Eonasdan** [comment]
@cwolcott your input does not match the provided format. `L LT` is shorthand for the locales default date time

**Comment by cwolcott** [comment]
Ok, it work just fine in 6.2.7 and 6.2.10.  No of my code has changed.  I was just upgrading to 6.4.4.  I will take a look at your docs to see what I am missing.

**Comment by cwolcott** [comment]
So like I said above no code has changed and all I was doing was upgrading from v6.2.10 to v6.4.4.  The code that is having an issue now with v6.4.4 is:

```
detailsEndDatePicker.dates.setFromInput(notebookDetails['END_DATE'] + ' 00:00:00');
```

I am passing in a string that looks like **'2022-03-19 00:00:00'**.  In v6.2.10 the string displayed just fine in the tempusDominus input field.
![image](https://user-images.githubusercontent.com/3777526/228991963-e299b0cf-3bc7-4442-bfa6-374af80d7d0e.png)

The input is defined in the following manner:
```
    detailsEndDatePicker = new tempusDominus.TempusDominus(document.getElementById('dtEndDate'),
        {
            display: {
                viewMode: 'calendar',
                components: {month: false, date: true, clock: false },
                buttons: { today: true, clear: true, close: true },
            },
            useCurrent: false,
            localization: {
                dayViewHeaderFormat: { month: 'long', year: 'numeric' }
            },
        });
```

Any thoughts why this is no causing issues in v6.4.4?

**Comment by Eonasdan** [comment]
I'm going to close this. Please let me know if the format tokens do not solve your issue

**Comment by chrisskalog** [comment]
So @Eonasdan if I remember correctly, in the previous version, the format of the date - time was selected automatically from the locale. 
How are we supposed to do this now ? Can you provide a code sample ?

**Comment by Eonasdan** [comment]
Previously I was guessing using Intl. However, it doesn't provide much flexibility and was sometimes wrong. You need to set [`localization.format`](https://getdatepicker.com/6/options/localization.html#format) to whatever token string you want it to be. I think all the locales have appropriate strings already defined if you'd rather just include those.

**Comment by chrisskalog** [comment]
Honestly, I am not sure where to get those appropriate strings. If you can provide some info and if it works then I am fine with it.
Can you point me to some directlon ? 

Thanks

**Comment by Eonasdan** [comment]
It was in my previous post https://getdatepicker.com/6/plugins/customDateFormat.html
