### ISSUE TITLE
Example: Enabled/Disabled Dates broken

### ISSUE THREAD

**Issue by cwolcott** [Eonasdan/tempus-dominus#2784]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

The example **Enabled/Disabled Dates** is currently broken:

All other examples are working, but are using version v6.2.6 instead of the latest v6.4.4

### StackBlitz fork

Looking at your [REPL](https://getdatepicker.com/6/repl.html) page

Line 3 uses `new tempusDominus.TempusDominus` instead of just `new TempusDominus`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.6

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Hello 6.7.7 should resolve this.
