### ISSUE TITLE
calendarWeeks displays only the first week of the month for all weeks

### ISSUE THREAD

**Issue by ChistokhinSV** [Eonasdan/tempus-dominus#2786]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

calendarWeeks displays only the first week of the month for all weeks.

The problem appears on all versions of 6.4.X
Does not show up on 6.2

![calendarWeeks](https://user-images.githubusercontent.com/6992480/229350217-573d0671-cf1a-4b4d-9c00-78df02967a43.png)

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-4q46rg?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.4.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en

**Comment by Eonasdan** [comment]
Hello 6.7.7 should resolve this.
