### ISSUE TITLE
Infinite loop, browser freeze

### ISSUE THREAD

**Issue by ivanhennig** [Eonasdan/tempus-dominus#2788]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I've create an instance using the following options:

```js
  {
    localization: {
      locale: 'default',
      selectTime: 'Mudar para hora',
      selectDate: 'Mudar para data',
      format: 'L LT',
      dateFormats: {
        LTS: 'HH:mm:ss',
        LT: 'HH:mm',
        L: 'dd/MM/yyyy',
        LL: 'd [de] MMMM [de] yyyy',
        LLL: 'd [de] MMMM [de] yyyy H:mm',
        LLLL: 'dddd, d [de] MMMM [de] yyyy H:mm',
      },
    },
    display: {
      icons: {
        time: 'bi bi-clock',
        date: 'bi bi-calendar3',
        up: 'bi bi-chevron-compact-up',
        down: 'bi bi-chevron-compact-down',
        previous: 'bi bi-chevron-compact-left',
        next: 'bi bi-chevron-compact-right',
        today: 'bi bi-calendar2-check',
        clear: 'bi bi-trash3',
        close: 'bi bi-x-lg',
      },
      components: {
        calendar: true,
        date: true,
        month: true,
        year: true,
        decades: true,
        clock: true,
        hours: true,
        minutes: true,
        seconds: false,
      },
      buttons: {
        clear: true,
        close: true,
      },
    },
    dateRange: true,
    useCurrent: 'day',
    stepping: 10,
  }
```
Please note the dateRange in options. Things runs fine clicking in the start and the end date of a range, however if the user clicks twice on the same date the browser just hang

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-xbdyek?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.4.4

### What your browser's locale? You can find this information from the sample StackBlitz.

 pt-BR

**Comment by Eonasdan** [comment]
Hello 6.7.7 is published with this fix. Thanks again
