### ISSUE TITLE
REPL Demo Parent Container broken in 6.2.6

### ISSUE THREAD

**Issue by Liebeck** [Eonasdan/tempus-dominus#2795]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

https://getdatepicker.com/6/repl.html
Go to "parent container"

The example is broken. The error message is 

`Error in /turbo_modules/@eonasdan/tempus-dominus@6.2.6/dist/js/tempus-dominus.js (564:27)
TD: No element was provided.`

### StackBlitz fork

none

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.6

### What your browser's locale? You can find this information from the sample StackBlitz.

de-De

**Comment by Eonasdan** [comment]
Hello 6.7.7 should resolve this.
