### ISSUE TITLE
MultipleDates not showing active badge anymore

### ISSUE THREAD

**Issue by Liebeck** [Eonasdan/tempus-dominus#2796]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Beginning with version 6.4.1 (and latest 6.4.4), the picker does not add the 'active' class to the clicked date anymore. This results in selected dates not being highlighted anymore. Downgrading to 6.2.9 revealed to me that my code is working and that the bug started in 6.4.1

Looking at the 6.4.1 diff, I can see this change https://github.com/Eonasdan/tempus-dominus/commit/7b4622c3f17e6303510bffcbc5c7975242cf4de1#diff-2ba219d378add7c5eec0f4fed2e1599d032c4282b5b7546ac6aa7a1982c29890R109

@Eonasdan  I think you flipped the boolean there. Instead of 
`!this.optionsStore.options.multipleDates &&`
it should probably be
`this.optionsStore.options.multipleDates &&`
?

### StackBlitz fork

none

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.4.4

### What your browser's locale? You can find this information from the sample StackBlitz.

de-DE

**Comment by Eonasdan** [comment]
Hello 6.7.7 should resolve this.

**Comment by Liebeck** [comment]
@Eonasdan Thank you very much! ❤️ I can confirm that 6.7.7 fixes that issue.

FYI: You shipped a console.log(index) (https://github.com/Eonasdan/tempus-dominus/pull/2803/files#diff-9cb33452562adbb370a88113a5e9699d66b6b5715b51e88ff959d21f2fc34309R342) into the production build
