### ISSUE TITLE
bower eonasdan-bootstrap-datetimepicker#^4.17.47 UNABLE_TO_GET_ISSUER_CERT_LOCALLY Request to https://registry.bower.io/packages/eonasdan-bootstrap-datetimepicker failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by 273299007** [Eonasdan/tempus-dominus#2806]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

bower install eonasdan-bootstrap-datetimepicker#^4.17.47
......
bower eonasdan-bootstrap-datetimepicker#^4.17.47UNABLE_TO_GET_ISSUER_CERT_LOCALLY Request to https://registry.bower.io/packages/eonasdan-bootstrap-datetimepicker failed: unable to get local issuer certificate

Thank you so much in advance.!

bower.json

  "dependencies": {
    "bootstrap": "3.3.4",
    "handlebars": "3.0.0",
    "datatables": "Datatables/DataTables#1.10.6",
    "datatables-tabletools": "2.2.4",
    "datatables-responsive": "1.0.5",
    "moment": "2.10.6",
    "bootstrap-datepicker": "1.4.0",
    **"eonasdan-bootstrap-datetimepicker": "^4.17.47"**
  }

bower -v
1.8.14

 node -v
v10.16.0

### StackBlitz fork

n/a

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

eonasdan-bootstrap-datetimepicker#^4.17.47

### What your browser's locale? You can find this information from the sample StackBlitz.

en-us

**output of npm config  list**

; cli configs
metrics-registry = "https://registry.bower.io/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.0 win32 x64"

; userconfig C:\Users\...\.npmrc
registry = "https://registry.bower.io/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\src\....\Content
; HOME = C:\Users\...
; "npm config ls -l" to show all defaults.

**Comment by 273299007** [comment]
npm config  list
; cli configs
metrics-registry = "https://registry.bower.io/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.0 win32 x64"

; userconfig C:\Users\...\.npmrc
registry = "https://registry.bower.io/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\src\....\Content
; HOME = C:\Users\...
; "npm config ls -l" to show all defaults.

**Comment by Eonasdan** [comment]
As I mentioned to you elsewhere, I don't have time to support bower or version 4 anymore. `unable to get local issuer certificate` sounds like it's on your end. You could also try opening an issue with bower.
