### ISSUE TITLE
Update the date without selecting/clicking a day

### ISSUE THREAD

**Issue by Antoniafriedrich** [Eonasdan/tempus-dominus#2811]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [x] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

I am able to select "YY", "YY/MM" or any other format that do not feature day in it. 
However, regardless of  format my datetime value in the input field does not update unless I select the day.

When selecting time, the values for hours, minutes and seconds update in my formfield in real time and not only when you select the smallest value. This function should exist for date as well.

### Motivation and context

This function is usefull for formats that have no day component as well as for formats that do have a day component. 

Users might accidently select an incorrect month or year in their selection but not notice until their date selection is complete. If they attempt to go back and select a different month, they might not select a day again, because the day was already correctly selected. They would expect the form to automatically update with the new selection even without selecting a day. In that case they would unknowingly submit an inaccurate date, if they do not double check.

**Comment by Eonasdan** [comment]
Hello, please try the following configuration and let me know if this meets your needs.

```ts
{
  display: {
    components: {
      clock: false,
      date: false
    }
  },
  localization: {
    format: 'yy/MM'
  }
}
```

**Comment by Antoniafriedrich** [comment]
Hello and thank you for your response! Unfortunatelly this did not help solving my problem.
I think there was a slight misunderstanding, even if this gives me a good example to explain better what I meant. 

How it is now:
If the format is yy/MM it updates when selecting the month, when it is yy/MM/dd it updates when selecting the day. 

What I want:
When selecting the year the year updates, when selecting the month the month updates, when selecting the day the day updates, as in when I click the associated buttons, regardless of the format I am using. 

Thank you again and sorry for not being clear enough about it the first time.

**Comment by Eonasdan** [comment]
Hi 6.7.13 should be released shortly to solve this.

**Comment by Antoniafriedrich** [comment]
Thank you! Very great work!

**Comment by danni-filipovic** [comment]
This should DEFINITELY be optional. This is not standard or expected behaviour with datepickers. Just spent good three hours figuring out why my dates are changing when i am just clicking around, i was even trying to .setValue(event.details.oldDate) if modeView was !== 'calendar' etc. to fix this. Not everybody wants this and i suggest something like `allElementsUpdateValue: boolean`.

**Comment by Eonasdan** [comment]
I had to revert this. Sorry @Antoniafriedrich. This also broke multidates.
