### ISSUE TITLE
Format bug when selecting hour or minue

### ISSUE THREAD

**Issue by ukaytac** [Eonasdan/tempus-dominus#2816]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Hello,

When I choose/increment hours/minutes from picker, my format is changing. If I change the date the format remains the same.

Thanks a lot.

`var picker3 = new tempusDominus.TempusDominus(document.getElementById("event_start_date"), {
                            defaultDate: DateTimeVal,
                            display: {
                                viewMode: "calendar",
                                components: {
                                    decades: false,
                                    year: true,
                                    month: true,
                                    date: true,
                                    hours: true,
                                    minutes: true,
                                    seconds: false
                                }
                            },
                            localization: {
                                locale: "tr",
                                startOfTheWeek: 1,
                                format: 'DD.MM.YYYY HH:mm',
                                hourCycle: 'h24'
                            },
                        });

var DateTimeVal = moment(arg.start).toDate();
picker3.dates.setValue(tempusDominus.DateTime.convert(DateTimeVal));
`

![1](https://github.com/Eonasdan/tempus-dominus/assets/5268938/62f58320-d546-4e93-9bc1-e65c04b60018)
![2](https://github.com/Eonasdan/tempus-dominus/assets/5268938/3b3219b7-12d7-481c-bd36-0d54bad2f54a)
![3](https://github.com/Eonasdan/tempus-dominus/assets/5268938/502e78de-896f-4a4d-b3eb-912c07f45e6a)
![4](https://github.com/Eonasdan/tempus-dominus/assets/5268938/a14baa2e-d9e4-4e43-bc83-d1248b6cbaba)

### StackBlitz fork

customdateformat

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6

### What your browser's locale? You can find this information from the sample StackBlitz.

tr

**Comment by Eonasdan** [comment]
please create a stackblitz fork with your code
