### ISSUE TITLE
Locale pt-PT displays weekdays in long format causing words to overlap 

### ISSUE THREAD

**Issue by jasonmonroe** [Eonasdan/tempus-dominus#2817]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Locale pt-PT displays weekdays in long format causing words to overlap in the UI.  Please fix this by abbreviating the weekdays.  Thank you.

https://getdatepicker.com/6/plugins/customDateFormat.html
Locale: pt-PT

 

### StackBlitz fork

//using "window" is just for the stackblitz, you do not need to do this
// https://stackblitz.com/edit/tempus-dominus-v6-simple-setup?file=index.js
window.datetimepicker1 = new tempusDominus.TempusDominus(
  document.getElementById('datetimepicker1'),
  {
    localization: {
      dayViewHeaderFormat: { month: 'long', year: '2-digit' },
      locale: 'pt-PT',
      startOfTheWeek: 1
       }
      });

document.getElementById(
  'info'
).innerHTML = `Your browser's locale is ${navigator.language}.<br/>
You are using version ${tempusDominus.version}`;

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.2.10

### What your browser's locale? You can find this information from the sample StackBlitz.

pt-PT

**Comment by jasonmonroe** [comment]
There’s no code.  Just load the instance w/ localization object pt-PT.  When you click on the input the weekdays are overlapping.  Let me see if I can send a screenshot.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jasonmonroe** [comment]
https://tempus-dominus-v6-simple-setup-xlaqe3.stackblitz.io

**Comment by Eonasdan** [comment]
Thank you. I see the issue

**Comment by jasonmonroe** [comment]
@Eonasdan any updates? Are you going to simply abbreviate the weekdays in Portuguese or just only use the first three letters?

**Comment by jasonmonroe** [comment]
Thanks!

**Comment by Eonasdan** [comment]
I don't have any updates right now. There's not a good way for me to fix this easily at the moment. Those values come from `Intl`. In v7 I'll be looking at migrating these values to the locale scripts so that it can be customized.

**Comment by jasonmonroe** [comment]
> I don't have any updates right now. There's not a good way for me to fix this easily at the moment. Those values come from `Intl`. In v7 I'll be looking at migrating these values to the locale scripts so that it can be customized.

Is it possible to simply truncate or abbreviate the weekdays for pt-PT?

**Comment by Eonasdan** [comment]
> Those values come from Intl

Anything I do now will affect all locales. You are welcome to fork and modify the picker or overwrite the function that generates the weekdays yourself until I have time to work on this.

**Comment by jasonmonroe** [comment]
Which function does that? Can we just add a condition that checks the locale and if it's pt-PT do a sting limit of just 3 characters?

**Comment by Eonasdan** [comment]
Hello. This fixed with released with 6.7.19.  A new option was added, `maxWeekdayLength`. You can set that to whatever number you want.
