### ISSUE TITLE
Clicking on toggle meridiem button will submit the form

### ISSUE THREAD

**Issue by axunonb** [Eonasdan/tempus-dominus#2820]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When a time picker is created, and the `container` is set to an element inside the &lt;form&gt;, clicking on the toggle meridiem button will submit the form.

The reason is the the missing `type='button'` attribute to the meridiem button.
Adding the attribute will stop submitting the form when clicking this button.

```js
const timePicker = new tempusDominus.TempusDominus(element, {
    container: element,
    allowInputToggle: false,
    stepping: 15,
    localization: {
        format: 'LT'
    },
    display: {
        viewMode: 'clock',
        components: {
            decades: false,
            year: false,
            month: false,
            date: false,
            hours: true,
            minutes: true,
            seconds: false
        },
        buttons: {
            today: false,
            clear: true,
            close: true
        }
    }
});
```
So I guess the missing part is
```js
button.setAttribute('type', 'button'); 
```
to be added here:
https://github.com/Eonasdan/tempus-dominus/blob/efba21adbe7e29aa04f71e140d8f76c22c006548/src/js/display/time/time-display.ts#L291-L315

Should I submit a PR for this change?

### StackBlitz fork

https://tempus-dominus-v6-simple-setup-spewzx.stackblitz.io

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.7

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Sure, if you would like to submit a PR to add this, I'll gladly take it.
