### ISSUE TITLE
input field keep getting 12 hour format

### ISSUE THREAD

**Issue by jujutsucode** [Eonasdan/tempus-dominus#2842]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

i have use option
```
components: {
                hours: true,
                minutes: true,
                useTwentyfourHour: true,
            }
```

but the input field still displaying 12 hours format with am/pm.
how can i make the input field also 24hour format?

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-tk2cjm?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6.7.11

### What your browser's locale? You can find this information from the sample StackBlitz.

id-ID

**Comment by Eonasdan** [comment]
useTwentyfourHour is deprecated. You need to provide a format string to the localization property
