### ISSUE TITLE
allowInputToggle option broken in 6.7.10 and 6.7.11

### ISSUE THREAD

**Issue by nickalbrecht** [Eonasdan/tempus-dominus#2846]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I updated to a newer version of TempusDominus a while back, and it seems like it broke the `allowInputToggle` option after 6.7.7 

6.7.7 - Clicking on the input box opens the date picker, and allows you to select a date (correct)
6.7.10 - Clicking on the input box causes the picker to open, but it immediately close again. (bug) Note: Seem to be able to re-open it if you click on the input box a second time, with each subsequent click alternating between opening and closing the dialog
6.7.11 - Clicking on the input box causes the picker to open, but it immediately close again. (bug) Note: Subsequent clicks on the field do nothing and there doesn't seem to be any way to keep it open.

Verified the problem on Chrome, FireFox and Edge (since they are the browsers I have access to)
Verified behavior on Windows. On Android (chrome) it's slightly different in that the picker doesn't even open briefly, but still works on Android (chrome) as expected with 6.7.7.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-6iuss4?file=index.html

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.11

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by nickalbrecht** [comment]
GAH, I just noticed my search for closed issues was wrong. Looking at the existing issue now

**Comment by nickalbrecht** [comment]
Nope this is still valid, that was for 6.7.10 a month ago, and this is still present in 6.7.11. Was the hotfix for #2837 included in 6.7.11?

**Comment by Antal1609** [comment]
@nickalbrecht 6.7.11 was indeed the hotfix for #2837.

However, we are experiencing the same bug in our back-office. When you click on the input box, the date picker opens, but it immediately closes again. That said, if you open a new browser tab and return to the date picker, it is displayed correctly.

We think this is a conflict with another plugin. As the same picker works great in our front-office.

**Comment by Eonasdan** [comment]
This seems to be an issue just with using the picker without the icon toggle. I'll work on getting a patch out for this.

**Comment by Antal1609** [comment]
We have the icon toggle in place but it does not work in our back-office with the same HTML.

**Comment by Eonasdan** [comment]
Hi 6.7.13 should be released shortly to solve this.

**Comment by nickalbrecht** [comment]
Apologies for the long delay. I can confirm that after I updating, the issue appears to be resolved
