### ISSUE TITLE
Using multipleDates when components.date is disabled

### ISSUE THREAD

**Issue by erekle13** [Eonasdan/tempus-dominus#2849]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Hi, 

I was trying to make scenario when I can pick only month so I disabled 'components.date' but this does not work in combination with multipleDates, picks only the latest month. 

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-36ukmx?file=index.js

window.datetimepicker1 = $('#datetimepicker1').tempusDominus({
                    display: {
                        viewMode:'months',
                        components: {
                            calendar: true,
                            date: false,
                            month: true,
                            year: true,
                            decades: false,
                            clock: false,
                            hours: false,
                            minutes: false,
                            seconds: false,
                        },
                        //theme: 'auto'
                    },
                    localization: {
                        format: 'MMM yyyy',
                    },
                    multipleDates: true,
                    multipleDatesSeparator: '; ',
                });

### What operating system(s) are you seeing the problem on?

macOS

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.13

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Hi. Unfortunately, I won't be able to make this work for you. I had made a change a while back that would have supported this, but it caused other issues. 

This is the last week I'm doing free bug fixes for this project. If it's important to you (or your company), you can sponsor the issue. Please contact me first if you want to do that.
