### ISSUE TITLE
Highlights date when using useCurrent: false in v6.7.13

### ISSUE THREAD

**Issue by edgars-bi** [Eonasdan/tempus-dominus#2852]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Using v6.7.13 date auto selects when using option useCurrent: false

Steps:
1. Opening calendar and selecting then unselecting any date
2. Going back to choose month, year or decade the date is selected again

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-rcjdhp?file=index.js,index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

v6.7.13

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
Please check the latest version. I can't reproduce this. Feel free to update your SB example.
