### ISSUE TITLE
Patterns of DateTime.fromString and DateTime.format are not aligned

### ISSUE THREAD

**Issue by solomax** [Eonasdan/tempus-dominus#2855]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

`DateTime.fromString` can handle single `y` in the pattern https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/datetime.ts#L767

While `DateTime.format` can't: https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/datetime.ts#L921

So in case `localization.format` with single `y` is used (for ex. `dd.MM.y, HH:mm:ss`)
The date can be parsed correctly BUT being set into input as `27.09.undefined, 14:47:41` on select

### StackBlitz fork

https://codepen.io/solomax/pen/bGOeYKg

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.11, 6.7.13

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by solomax** [comment]
I believe the fix is trivial :)

single `y` should be handled exactly as `yyyy` :)))

**Comment by Eonasdan** [comment]
New release should fix this.
