### ISSUE TITLE
Usage of css variables for theming

### ISSUE THREAD

**Issue by AgentSmith0** [Eonasdan/tempus-dominus#2857]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

What about replacing hard coded css values by css variables.

### Motivation and context

This would make theming much easier (light/dark mode and using css variables from other css design frameworks).

**Comment by Eonasdan** [comment]
This is done in v6.9.4
