### ISSUE TITLE
Markup input value not load correctly when use time with meridiem p.m.

### ISSUE THREAD

**Issue by mario-alba** [Eonasdan/tempus-dominus#2860]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When HTML code contains markup input with predefined time value in meridiem p.m.,  tempus-dominud constructor not load the correct value, overriding p.m. to a.m.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-import-qau8ft?file=index.html,index.js

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.10

### What your browser's locale? You can find this information from the sample StackBlitz.

es-CO

**Comment by Eonasdan** [comment]
Hello. This fixed with released with 6.7.19.  A new option was added, `maxWeekdayLength`. You can set that to whatever number you want.
