### ISSUE TITLE
Call with Classname not with only  ID 

### ISSUE THREAD

**Issue by Bruskyer** [Eonasdan/tempus-dominus#2862]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

I have already used datetimepicker library  in my project its very usefull thanks for it, I encountered a problem during calling with #idname when I use for multiple input in same page I have to add every  id name into call function. I would like call it with class name and just add class to input to init the calender. is there any way make this or does datetimepicker support this feature?
thanks

### Motivation and context

Thanks in advance

**Comment by Eonasdan** [comment]
The picker expects a single element. The best thing for you to do is to do a foreach over your elements and create a picker for each one. I don't have time to do this feature right now.
