### ISSUE TITLE
viewDate is overriden by minDate

### ISSUE THREAD

**Issue by LePtitJoNadeau** [Eonasdan/tempus-dominus#2877]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

viewDate is overriden by minDate on navigation

(same thing to maxDate)

Step to reproduce bug:
1. Pickup tomorrow date
2. Open datetimepicker2
3. Click right arrow to go to next month
4. Try to left click to left arrow now. It's not available anymore.
Expected behavior: We should be able to go to previous month since the minDate picked is tommorrow.

### StackBlitz fork

https://tempus-dominus-v6-simple-setup-mldyhy.stackblitz.io/
Edit mode:
https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-mldyhy?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.19

### What your browser's locale? You can find this information from the sample StackBlitz.

fr-CA

**Comment by Eonasdan** [comment]
This is released with 6.9.4

**Comment by LePtitJoNadeau** [comment]
Thank you, have good holydays!
