### ISSUE TITLE
maxDate not selectable

### ISSUE THREAD

**Issue by SzoftverHaz** [Eonasdan/tempus-dominus#2879]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

When I set maxDate like this:
'updateOptions({
    restrictions: {
      maxDate: new Date('2024-11-20'),
    },
  });'
in calendar 20th looks like active but nothing happens when click on it, so it is not selectable

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-repl-jtub1v?file=example.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.19

### What your browser's locale? You can find this information from the sample StackBlitz.

hu-HU

**Comment by SzoftverHaz** [comment]
There is another bug. I added a second TD instance to this example that is not allow to select November. Maybe related to previous bug.

**Comment by SzoftverHaz** [comment]
I found another one and included this snippet as a third input. When <(previous decade) pressed, 2012 and 2013 can be selected only.

**Comment by Eonasdan** [comment]
The other issues you mentioned should be fixed in 6.9.4. The min/max date are time stamps. They are exclusive, so you will need to either set the time to midnight or pad the day by 1.

**Comment by SzoftverHaz** [comment]
Thank you!
