### ISSUE TITLE
"Short Weekday" (ddd) throws error when setting the value in the text input

### ISSUE THREAD

**Issue by AnatoliiPavlov** [Eonasdan/tempus-dominus#2884]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

It can be reproduced even in the demo https://getdatepicker.com/6/plugins/customDateFormat.html
The stackblitz example provides the same behavior.

1) Add 'ddd' to the beginning of format string so it will become 'ddd dd/MM/yyyy HH:mm'.
2) Press 'Change' button. Sample picker will update its value to something like 'ter. 05/12/2023 21:10'.
3) Add or subtract minutes (like 'ter. 05/12/2023 21:11') **directly in the text input** and press Enter
4) Observe the Dev Tools console - it will display an error 'errors.ts:140 Uncaught Error: TD: Custom Date Format: Unable to parse provided input: ter. 05/12/2023 21:11, format: ddd dd/MM/yyyy HH:mm'
5) Press picker icon - picker won't reflect your changes (it will display 21:10 instead of expected  21:11)

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-x2v18u?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.16

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
This is fixed in 6.9.4
