### ISSUE TITLE
_dateToDataValue() should not use formatted month and date

### ISSUE THREAD

**Issue by hkvstore** [Eonasdan/tempus-dominus#2886]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Currently the code is:
```ts
  private _dateToDataValue(date: DateTime): string {
    if (!DateTime.isValid(date)) return '';

    return `${date.year}-${date.monthFormatted}-${date.dateFormatted}`;
  }
```
If Arabic locale is used, the outputted HTML will be like:
![image](https://github.com/Eonasdan/tempus-dominus/assets/16445695/90ead690-42d5-452a-a9cc-b36c0a0aa4c8)

But the date value should not be formatted.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-hyrhpd?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.19

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Eonasdan** [comment]
this is done in 6.9.4
