### ISSUE TITLE
Manual writing date inside input not recognized/parsed like old datetimepicker v3

### ISSUE THREAD

**Issue by itajackass** [Eonasdan/tempus-dominus#2921]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).
- [X] I understand that only sponsored issues will be worked on and that if I wish to sponsor an issue, I will contact the owner FIRST.

### Describe the issue

Hi, with old "datetimepicker", all my input was initialized for italian standard:

   ` format: 'dd/MM/yyyy'`

Some user using "calendar icon" to select a date from calendar picker, other users manual write inside input to speedup form compiling.
For example, if a user need to select christmas day of year 2023, simply write:

   ` 251223`

inside input field!

With old datetimepicker it was automatic recognized, on focus out, and became '25/12/2023'

Now with new tempus dominus (v6) it seems this very good function is missing and I get:

    `TD: Custom Date Format: Unable to parse provided input: 251223, format: dd/MM/yyyy`

. Any change to restore this feature? Thanks

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-jquery-setup-n79xp8?file=index.js,index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

v6

### What your browser's locale? You can find this information from the sample StackBlitz.

it-IT

**Comment by Eonasdan** [comment]
I am no longer supporting this library for free.

The error is correct. The "date" that was entered is not in the correct format. Previous versions used momentjs to guess the input when the format was incorrect. v5+ doesn't use moment and therefore doesn't try to make guesses. I'd suggest some kind of input validator or mask
